翻译关于文档部分
cloudnativeto/envoy pull request #103
Opened 2020-11-05 12:20 UTC by lhb008

zh-translation:  `docs/root/about_docs.rst`

ref: https://github.com/cloudnativeto/envoy/issues/101
- [x] Docs

2020-11-05 23:03 UTC, addozhang commented
/review

2020-11-05 23:39 UTC, addozhang requested changes

2020-11-05 23:39 UTC, addozhang commented on docs/root/about_docs.rst
> +* :ref:`介绍 <intro>`: 这部分主要包含了什么是 Envoy，架构预览，典型部署等内容。
```suggestion
* :ref:`介绍 <intro>`: 这部分主要包含了什么是 Envoy、架构预览、典型部署等内容。
```

2020-11-05 23:39 UTC, addozhang commented on docs/root/about_docs.rst
> +* :ref:`配置 <config>`: 关于 Envoy 详细配置的说明书。与此相关地，配置指导也包含了统计信息，运行时配置和 API 等。
```suggestion
* :ref:`配置 <config>`: 关于 Envoy 详细配置的说明书。与此相关地，配置指导也包含了统计信息、运行时配置和 API 等。
```

2020-11-05 23:39 UTC, addozhang commented on docs/root/about_docs.rst
> +* :ref:`操作 <operations>`: 关于如何操作 Envoy 的常规信息，包括命令行，热重启包装器，管理界面，一个常规用的统计预览。
```suggestion
* :ref:`操作 <operations>`: 关于如何操作 Envoy 的常规信息，包括命令行、热重启包装器、管理界面、一个常规用的统计预览，等。
```

2020-11-06 02:17 UTC, majinghe commented on docs/root/about_docs.rst
> +* :ref:`操作 <operations>`: 关于如何操作 Envoy 的常规信息，包括命令行，热重启包装器，管理界面，一个常规用的统计预览。
嗯 好的，我改一下。这个确实是个疑惑点，英语中没有顿号。但是中文有顿号，改还是不改呢？

2020-11-06 02:21 UTC, addozhang commented on docs/root/about_docs.rst
> +* :ref:`操作 <operations>`: 关于如何操作 Envoy 的常规信息，包括命令行，热重启包装器，管理界面，一个常规用的统计预览。
我个人觉得顿号好点。

2020-11-06 06:37 UTC, majinghe commented
@addozhang  已经改过来了。全部用顿号表示了。

2020-11-06 06:39 UTC, addozhang approved these changes

2020-11-06 06:39 UTC, merged