zh-translation: /intro/what_is_envoy.rst
cloudnativeto/envoy pull request #112
Opened 2020-11-06 08:19 UTC by dyingbleed

ref: https://github.com/cloudnativeto/envoy/issues/49

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +Envoy 是专为大型现代服务架构而设计的通信总线和 L7 代理。该项目源于以下理念：
```suggestion
Envoy 是为面向大型现代服务架构而设计的 L7 代理和通信总线。该项目源于以下理念：
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +事实上，实现上述的目标非常困难。为了做到这一点，Envoy 提供了以下高级特性：
```suggestion
事实上，实现上述的目标非常困难。Envoy 试图通过提供以下高级功能来实现这一目标：
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +    Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。
```suggestion
    一个 Envoy 部署就可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +可插拔的 :ref:`filter <arch_overview_network_filters>` 链机制允许开发人员编写 filter 来执行不同 TCP/UDP 代理任务并将其插入到主服务中。
```suggestion
可插拔的 :ref:`filter <arch_overview_network_filters>` 链机制允许开发 filter 来执行不同 TCP/UDP 代理任务并将其插入到主服务中。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +:ref:`Redis <arch_overview_redis>`、:ref:`MongoDB <arch_overview_mongo>` 和 :ref:`Postgres <arch_overview_postgres>` 等等。
```suggestion
:ref:`Redis <arch_overview_redis>`、:ref:`MongoDB <arch_overview_mongo>` 和 :ref:`Postgres <arch_overview_postgres>` 等。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +可以将 HTTP filter 插入 HTTP 执行不同任务的连接管理子系统中，如 :ref:`buffering <config_http_filters_buffer>`、:ref:`rate limiting
```suggestion
可以将 HTTP filter 插入执行不同任务的 HTTP 连接管理子系统中，如 :ref:`缓存 <config_http_filters_buffer>`、:ref:`限速
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +<arch_overview_global_rate_limit>`、:ref:`routing/forwarding <arch_overview_http_routing>`、
```suggestion
<arch_overview_global_rate_limit>`、:ref:`路由/转发 <arch_overview_http_routing>`、
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +嗅探 Amazon 的 :ref:`DynamoDB <arch_overview_dynamo>` 等等。
```suggestion
嗅探 Amazon 的 :ref:`DynamoDB <arch_overview_dynamo>` 等。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +建议配置所有服务之间的 Envoy 使用 HTTP/2 来创建持久连接的网格，以便可以复用请求和响应。
```suggestion
建议配置所有服务之间的 Envoy 使用 HTTP/2 来创建持久连接的网格，以便可以实现请求和响应的多路复用。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +**HTTP L7 路由：**当以 HTTP 模式运行时，Envoy 支持一种:ref:`routing <arch_overview_http_routing>`子系统，能够根据路径、权限、内容类型、:ref:`运行时 <arch_overview_runtime>`参数值等对请求进行路由和重定向。
```suggestion
**HTTP L7 路由：**当以 HTTP 模式运行时，Envoy 支持一种:ref:`路由 <arch_overview_http_routing>`子系统，能够根据路径、权限、内容类型、:ref:`运行时 <arch_overview_runtime>`参数值等对请求进行路由和重定向。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +这项功能在将 Envoy 用作前端/边缘代理时非常有用，同时，在构建服务网格时也会使用此功能。
```suggestion
这项功能在将 Envoy 用作前端/边缘代理时非常有用，同时在构建服务网格时也会使用此功能。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +**服务发现和动态配置：**Envoy 可以选择使用:ref:`dynamic configuration APIs <arch_overview_dynamic_config>` 的分层集合实现集中管理。
```suggestion
**服务发现和动态配置：**Envoy 可以选择使用一组分层的:ref:`动态配置 API <arch_overview_dynamic_config>` 来实现集中化管理。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +这些层为Envoy 提供了以下内容的动态更新：后端集群内的主机、后端集群本身、HTTP 路由、监听套接字和加密材料。
```suggestion
这些层为 Envoy 提供了以下内容的动态更新：后端集群内的主机、后端集群本身、HTTP 路由、监听套接字和加密材料。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +对于更简单的部署，可以:ref:`通过 DNS 解析 <arch_overview_service_discovery_types_strict_dns>`（甚至:ref:`完全跳过 <arch_overview_service_discovery_types_static>`）发现后端主机，静态配置文件将替代更深的层。
```suggestion
对于一个简单的部署，可以:ref:`通过 DNS 解析 <arch_overview_service_discovery_types_strict_dns>`（甚至:ref:`完全跳过 <arch_overview_service_discovery_types_static>`）发现后端主机，使用静态配置文件将替代深层配置。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +以及 HTTP L7 :ref:`routing <arch_overview_http_routing>`。
```suggestion
以及 HTTP L7 :ref:`路由 <arch_overview_http_routing>`。
```

2020-11-06 09:19 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +**绝佳的可观察性：**如上所述，Envoy 的主要目标是让网络透明化。
```suggestion
**最佳可观察性：**如上所述，Envoy 的主要目标是让网络透明化。
```

2020-11-07 06:22 UTC, hzliangbin requested changes

2020-11-07 06:22 UTC, hzliangbin commented on docs/root/intro/what_is_envoy.rst
> +所有的 Envoy 形成一个透明的通信网格，每个应用于本地主机收发信息，对网络的拓扑结构无感知。
此处是否笔误？应为 每个应用与本地主机收发信息 符合英文原意。或者本地主机不翻译，保留localhost。

2020-11-07 06:22 UTC, hzliangbin commented on docs/root/intro/what_is_envoy.rst
> +这意味着它可以桥接 HTTP/1.1 和 HTTP/2 客户端以及目标服务器的任意组合。
This means that any combination of HTTP/1.1 and HTTP/2 clients and target servers can be bridged。
这句话的意思应该是 客户端和目标服务器之间，任意的http协议组合都可以通信。即：
http1.1 client <-> http 1.1 server
http1.1 client <-> http 2 server
http2 client <-> http 1.1 server
http2 client <-> http 2 server。
英文原文的意思没有被很恰当的翻译出来。

2020-11-12 02:01 UTC, majinghe commented
@dyingbleed   有新的comment。烦请处理一下。多谢

2020-11-12 02:18 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +所有的 Envoy 形成一个透明的通信网格，每个应用于本地主机收发信息，对网络的拓扑结构无感知。
fix it

2020-11-12 02:28 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +**绝佳的可观察性：**如上所述，Envoy 的主要目标是让网络透明化。
What's the difference between 绝佳的 and 最佳?

2020-11-12 02:35 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +以及 HTTP L7 :ref:`routing <arch_overview_http_routing>`。
fix it

2020-11-12 02:37 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +这些层为Envoy 提供了以下内容的动态更新：后端集群内的主机、后端集群本身、HTTP 路由、监听套接字和加密材料。
fix it

2020-11-25 09:31 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +**绝佳的可观察性：**如上所述，Envoy 的主要目标是让网络透明化。
以平常翻译为准吧，一般在翻译中都是最佳，很少说绝佳的。

2020-11-25 09:31 UTC, helight commented
@dyingbleed 如果有修复，要提交一下哈

2020-11-26 06:58 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +Envoy 是专为大型现代服务架构而设计的通信总线和 L7 代理。该项目源于以下理念：
fix it

2020-11-26 06:58 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +事实上，实现上述的目标非常困难。为了做到这一点，Envoy 提供了以下高级特性：
fix it

2020-11-26 07:03 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +    Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。
一个如果直译过来的话感觉有些奇怪

2020-11-26 07:10 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +可插拔的 :ref:`filter <arch_overview_network_filters>` 链机制允许开发人员编写 filter 来执行不同 TCP/UDP 代理任务并将其插入到主服务中。
fix it

2020-11-26 07:10 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +:ref:`Redis <arch_overview_redis>`、:ref:`MongoDB <arch_overview_mongo>` 和 :ref:`Postgres <arch_overview_postgres>` 等等。
fix it

2020-11-26 07:13 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +可以将 HTTP filter 插入 HTTP 执行不同任务的连接管理子系统中，如 :ref:`buffering <config_http_filters_buffer>`、:ref:`rate limiting
fix it

2020-11-26 07:13 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +<arch_overview_global_rate_limit>`、:ref:`routing/forwarding <arch_overview_http_routing>`、
fix it

2020-11-26 07:13 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +嗅探 Amazon 的 :ref:`DynamoDB <arch_overview_dynamo>` 等等。
fix it

2020-11-26 07:15 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +建议配置所有服务之间的 Envoy 使用 HTTP/2 来创建持久连接的网格，以便可以复用请求和响应。
fix it

2020-11-26 07:15 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +**HTTP L7 路由：**当以 HTTP 模式运行时，Envoy 支持一种:ref:`routing <arch_overview_http_routing>`子系统，能够根据路径、权限、内容类型、:ref:`运行时 <arch_overview_runtime>`参数值等对请求进行路由和重定向。
fix it

2020-11-26 07:17 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +**服务发现和动态配置：**Envoy 可以选择使用:ref:`dynamic configuration APIs <arch_overview_dynamic_config>` 的分层集合实现集中管理。
fix it

2020-11-26 07:25 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +这意味着它可以桥接 HTTP/1.1 和 HTTP/2 客户端以及目标服务器的任意组合。
这意味着任意 HTTP/1.1 和 HTTP/2 客户端和目标服务器的组合都可以桥接在一起。

2020-11-26 07:43 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +**绝佳的可观察性：**如上所述，Envoy 的主要目标是让网络透明化。
fix it

2020-11-26 07:43 UTC, majinghe commented
@helight 振文 这个 PR 提交了，修改了，你看一下。辛苦。

2020-11-26 07:44 UTC, majinghe commented
@hzliangbin 梁斌 这个 pr 你也看一下。

2020-11-26 07:47 UTC, majinghe commented on docs/root/intro/what_is_envoy.rst
> +统计信息也可以通过:ref:`管理 <operations_admin_interface>`端口查看。
```suggestion
统计信息也可以通过 :ref:`管理 <operations_admin_interface>`端口查看。
```

2020-11-26 08:00 UTC, dyingbleed commented on docs/root/intro/what_is_envoy.rst
> +对于更简单的部署，可以:ref:`通过 DNS 解析 <arch_overview_service_discovery_types_strict_dns>`（甚至:ref:`完全跳过 <arch_overview_service_discovery_types_static>`）发现后端主机，静态配置文件将替代更深的层。
fix it

2020-11-26 12:21 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +    Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。
或者是：单个 Envoy 部署
原意这个 single 要翻译出来吧

2020-11-30 01:13 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +  * Envoy 适用于任何应用编程语言。Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。在面向服务架构中     ，使用多种应用框架和编程语言变得越来越普遍。Envoy 弥合了它们之间的差异。
```suggestion
  * Envoy 适用于任何应用编程语言。Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。在面向服务架构中，使用多种应用框架和编程语言变得越来越普遍。Envoy 弥合了它们之间的差异。
```

2020-11-30 01:14 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +  * 任何与面向大型服务架构打过交道的人都知道部署和升级软件库非常的痛苦。Envoy 可以透明地在整个基础架构上快速部署和     升级。
```suggestion
  * 任何与面向大型服务架构打过交道的人都知道部署和升级软件库非常的痛苦。Envoy 可以透明地在整个基础架构上快速部署和升级。
```

2020-11-30 01:15 UTC, helight commented on docs/root/intro/what_is_envoy.rst
> +  * 任何与面向大型服务架构打过交道的人都知道部署和升级软件库非常的痛苦。Envoy 可以透明地在整个基础架构上快速部署和     升级。
提交后也多看一下，基本的格式问题要保证没有。

2020-11-30 02:17 UTC, hzliangbin commented on docs/root/intro/what_is_envoy.rst
> +  * Envoy 适用于任何应用编程语言。Envoy 部署可以在 Java、C++、Go、PHP、Python 等之间形成一个网格。在面向服务架构中     ，使用多种应用框架和编程语言变得越来越普遍。Envoy 弥合了它们之间的差异。
Envoy 部署可以在 Java、C++、Go、PHP、Python 等不同语言编写的应用之间形成一个网格

2020-11-30 02:17 UTC, hzliangbin commented on docs/root/intro/what_is_envoy.rst
> +**前端/边缘代理支持**：在边缘使用相同的软件大有好处（可观察性、管理、相同的服务发现和负载均衡算法等）。Envoy 包含足够多的功能，使其可作为大多数现代 Web 应用程序的边缘代理。包括 :ref:`TLS <arch_overview_ssl>` 终止、HTTP/1.1 和 HTTP/2 :ref:`支持 <arch_overview_http_protocols>`，以及 HTTP L
Envoy包含足够多的功能，可作为

2020-11-30 10:11 UTC, hzliangbin approved these changes

2020-11-30 10:19 UTC, majinghe commented
@addozhang @helight @hzliangbin  三位帮看一下。这个还有没有什么问题。这个是打算发到公众号上的。

2020-11-30 11:27 UTC, helight commented
/LGTM
/approve

2020-11-30 11:28 UTC, helight commented
/approved

2020-11-30 11:28 UTC, helight approved these changes

2020-11-30 11:29 UTC, merged