zh-translation: /intro/arch_overview/upstream/cluster_manager.rst
cloudnativeto/envoy pull request #137
Opened 2020-11-12 09:29 UTC by webup

ref: https://github.com/cloudnativeto/envoy/issues/74

2020-11-13 06:23 UTC, shenhonglei commented
/review

2020-11-13 07:01 UTC, shenhonglei reviewed
@webup 仅供参考哈。

2020-11-13 07:01 UTC, shenhonglei commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +集群管理器已知的集群可以静态配置，也可以通过集群发现服务（CDS）API 动态获取。动态集群获取允许在中央配置服务器中存储更多的配置，因此需要更少的 Envoy 重启和配置分发。
```suggestion
集群管理器获取集群的方式可以是静态配置，也可以通过集群发现服务（CDS）API 动态获取。动态集群获取允许将更多配置存储在中央配置服务器中，这样就可以减少重启 Envoy 和重新分配配置的次数。
```
@webup 仅供参考哈

2020-11-13 07:01 UTC, shenhonglei commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +当集群在服务器启动时以及通过 CDS 进行初始化时，它们会被“预热”。这意味着，在进行以下操作之前，集群不会变得可用。
```suggestion
当集群在服务器启动时以及通过 CDS 进行初始化时，它们会被“预热”。这意味着，在进行以下操作之前，集群不可用。
```
@webup 仅供参数哈

2020-11-13 07:01 UTC, shenhonglei commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +前面几项保证了 Envoy 在开始使用集群进行流量服务之前，对集群有一个准确的认识。
```suggestion
以上几项确保 Envoy 在开始将集群用于流量服务之前，具有准确的集群视图。
```
@webup 仅供参考哈

2020-11-13 07:01 UTC, shenhonglei commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* 对于新添加的集群，在 Envoy 的其他部分看来，该集群不存在，直到它被预热。例如，引用集群的 HTTP 路由将导致 404 或 503（取决于配置）。
```suggestion
* 对于新添加的集群，在集群预热之前对于 Envoy 的其余部分来说是不可见的。例如，引用集群的 HTTP 路由将导致 404 或 503（取决于配置）。
```
@webup 仅供参考哈

2020-11-18 08:07 UTC, majinghe commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +考虑到上游集群和主机可用于任何数量的不同代理任务，上游集群和主机从网络或 HTTP 过滤栈中被抽象出来。集群管理器向过滤器堆栈暴露了 API，允许过滤器获得一个到上游集群的 L3/L4 连接，或者一个到上游集群的抽象 HTTP 连接池的句柄（上游主机是否支持 HTTP/1.1 或 HTTP/2 是隐藏的）。过滤器阶段决定它是否需要一个 L3/L4 连接或一个新的 HTTP 流，集群管理器处理所有
```suggestion
考虑到上游集群和主机可用于任何数量的不同代理任务，上游集群和主机从网络或 HTTP 过滤栈中被抽象出来。集群管理器向过滤器堆栈暴露了 API，允许过滤器获得一个到上游集群的 L3/L4 连接，或者一个到上游集群的抽象 HTTP 连接池的句柄（上游主机是否支持 HTTP/1.1 或 HTTP/2 是隐藏的）。过滤器阶段决定它是否需要一个 L3/L4 连接或一个新的 HTTP 流，集群管理器处理所有复杂的事情，包括知道哪些主机是可用的和健康的、负载均衡情况、上游连接数据的线程本地存储情况（因为大多数 Envoy 代码都是写成单线程的）、上游连接类型（TCP/IP，UDS）以及适用的上游协议（HTTP/1.1，HTTP/2）等。
```

2020-11-18 08:07 UTC, majinghe commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* 集群管理器 :ref:`配置 <config_cluster_manager>`
```suggestion
* 集群管理器 :ref:`配置 <config_cluster_manager>` 。
```

2020-11-18 08:07 UTC, majinghe commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* CDS :ref:`配置 <config_cluster_manager_cds>`
```suggestion
* CDS :ref:`配置 <config_cluster_manager_cds>` 。
```

2020-11-18 08:07 UTC, majinghe commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* CDS :ref:`配置 <config_cluster_manager_cds>`
末尾是不是少了两个句号

2020-11-20 10:05 UTC, webup commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* 集群管理器 :ref:`配置 <config_cluster_manager>`
这个我特意不留的，因为这个列表里面是两个词组，不是句子

2020-11-20 10:06 UTC, webup commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* CDS :ref:`配置 <config_cluster_manager_cds>`
上面解释了，因为是词组，特意没留句号

2020-11-21 13:00 UTC, addozhang requested changes

2020-11-21 13:00 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +* 集群管理器 :ref:`配置 <config_cluster_manager>`
@webup 这个统一一下吧，不改变原文的设置。

2020-11-21 13:00 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/cluster_manager.rst
> +当集群在服务器启动时以及通过 CDS 进行初始化时，它们会被“预热”。这意味着，在进行以下操作之前，集群不会变得可用。
嗯 @shenhonglei 的翻译更顺些。
要我可能会翻译成：直接进行以下操作，集群才可用。

2020-11-24 08:39 UTC, shenhonglei commented
/LGTM

2020-11-24 08:40 UTC, merged