zh-translation: docs/root/intro/arch_overview/other_protocols/postgre…
cloudnativeto/envoy pull request #141
Opened 2020-11-12 12:18 UTC by scilla0531

…s.rst

ref: https://github.com/cloudnativeto/envoy/issues/60

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-11-13 02:56 UTC, majinghe commented on docs/root/intro/arch_overview/other_protocols/postgres.rst
> +* 解码会话信息。
这个 session 是不是不要翻译比较好。大家说 session 可能都知道怎么回事，但是说会话可能有点懵。

2020-11-13 02:57 UTC, majinghe commented
/LGTM

2020-11-15 05:43 UTC, scilla0531 commented
@majinghe 已修改

2020-11-16 09:33 UTC, hzliangbin requested changes

2020-11-16 09:33 UTC, hzliangbin commented on docs/root/intro/arch_overview/other_protocols/postgres.rst
> +Postgres 过滤器的主要目标是捕获运行时统计信息，而不会影响或对 Postgres 上游服务器产生任何负载，因为这对它是透明的。该过滤器当前提供以下功能：
这对它是透明的，这个它指谁？可以明确一下。

2020-11-16 09:33 UTC, hzliangbin commented on docs/root/intro/arch_overview/other_protocols/postgres.rst
> -* Identify errors and notices backend responses.
Identify errors and notices backend responses.
识别 后端响应的错误和通知。这里的notices是应该是名词，和errors同为复述，并列。如果截断的话，应该是为
Identify errors and notice backend responses. notice不应该有复数形式。供参考

2020-11-17 10:23 UTC, scilla0531 commented
@hzliangbin 特别感谢，review超级细致。麻烦看下我修改的对不对哈，如有还有问题我再修改

2020-11-19 06:02 UTC, hzliangbin approved these changes
/LGTM

2020-11-19 06:03 UTC, merged