zh-translation: /intro/arch_overview/upstream/service_discovery.rst
cloudnativeto/envoy pull request #158
Opened 2020-11-13 15:43 UTC by webup

ref: https://github.com/cloudnativeto/envoy/issues/53

2020-11-14 02:17 UTC, hzliangbin requested changes, later dismissed

2020-11-14 02:17 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
“并将从任何现有的连接池中排出流量”，排出流量的说法有点奇怪。可以考虑意译。

2020-11-14 02:17 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +如果启用了 :ref:`respect_dns_ttl <envoy_v3_api_field_config.cluster.v3.Cluster.respect_dns_ttl>`，则使用 DNS 记录 TTL 和 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 来控
最小值为0

2020-11-14 02:17 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +这种服务发现类型是必须通过 DNS 访问的大规模网络服务的最佳选择。这类服务通常使用轮询 DNS 来返回许多不同的 IP 地址。通常情况下，每次查询都会返回不同的结果。如果在这种情况下使用严格 DNS，Envoy 会认为集群的成员在每个解析间隔期间都在变化，这将导致消耗连接池、连接循环等。取而代之的是，使用逻辑 DNS，连接会保持存活，直到它们被循环。当与大规模 Web 服务交互时，这是所有可能
这是所有可能的情况中最好的一种：

2020-11-14 02:17 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
一次成功的 DNS 解析

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +静态是最简单的服务发现类型。配置中明确规定了每个上游主机的解析网络名（IP 地址/端口、Unix 域套接字等）。
```suggestion
静态是最简单的服务发现类型。配置中明确指定了每个上游主机的解析网络名（IP 地址/端口、Unix 域套接字等）。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
```suggestion
当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将认为集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机被从结果中删除，Envoy 会认为它不再存在，并将从任何现有的连接池中驱逐流量。因此，如果一个成功的 DNS 解析返回 0 个主机，Envoy 将认为该集群没有任何主机。请注意，Envoy 从不同步解析转发路径中的 DNS。以牺牲最终的一致性为代价，永远不会担心在长期运行的 DNS 查询上出现阻塞。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +如果多个 DNS 名解析到同一个 IP，健康检查将 *不共享*。这意味着，如果使用主动健康检查与解析到相同 IP 的 DNS 名，应注意：如果一个 IP 在 DNS 名之间多次重复，可能会对上游主机造成不必要的负载。
```suggestion
如果多个 DNS 名解析到同一个 IP，健康检查将 *不共享*。这意味着，在使用解析到相同 IP 的 DNS 名做主动健康检查时需要注意：如果一个 IP 在 DNS 名之间多次重复，可能会对上游主机造成不必要的负载。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +如果启用了 :ref:`respect_dns_ttl <envoy_v3_api_field_config.cluster.v3.Cluster.respect_dns_ttl>`，则使用 DNS 记录 TTL 和 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 来控
```suggestion
如果启用了 :ref:`respect_dns_ttl <envoy_v3_api_field_config.cluster.v3.Cluster.respect_dns_ttl>`，则使用 DNS 记录 TTL 和 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 来控制 DNS 刷新率。对于严格的 DNS 集群，如果所有记录 TTL 的最小值为 0 ，则 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 用于控制 DNS 刷新率。 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 如果没有指定，默认为 5000ms。:ref:`dns_failure_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_failure_refresh_rate>` 控制故障时的刷新频率，如果没有配置，将使用 DNS 刷新率。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +逻辑 DNS 使用与严格 DNS 类似的异步解析机制。但是，逻辑 DNS 集群不是严格地取 DNS 查询的结果，并假设它们包含整个上游集群，而是只在 *需要启动新连接时* 才使用返回的第一个 IP 地址。因此，一个逻辑连接池可能包含到各种不同上游主机的物理连接。连接永远不会被耗尽，包括在 DNS 解析成功，返回 0 个主机的情况下。
```suggestion
逻辑 DNS 使用与严格 DNS 类似的异步解析机制。但是，逻辑 DNS 集群不是严格地取 DNS 查询的结果，并认为它们包含整个上游集群，而是只在 *需要建立新连接时* 才使用返回的第一个 IP 地址。因此，一个逻辑连接池可能包含到各种不同上游主机的物理连接。连接永远不会被驱逐，包括在 DNS 解析成功，返回 0 个主机的情况下。
```
这里 drain 不应该是耗尽，而是在 dns 没有结果返回时，已经建立的连接也不会被驱逐，不会主动断开。

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +这种服务发现类型是必须通过 DNS 访问的大规模网络服务的最佳选择。这类服务通常使用轮询 DNS 来返回许多不同的 IP 地址。通常情况下，每次查询都会返回不同的结果。如果在这种情况下使用严格 DNS，Envoy 会认为集群的成员在每个解析间隔期间都在变化，这将导致消耗连接池、连接循环等。取而代之的是，使用逻辑 DNS，连接会保持存活，直到它们被循环。当与大规模 Web 服务交互时，这是所有可能
```suggestion
这种服务发现类型是必须通过 DNS 访问的大规模网络服务的最佳选择。这类服务通常使用轮询 DNS 来返回许多不同的 IP 地址。通常情况下，每次查询都会返回不同的结果。如果在这种情况下使用严格 DNS，Envoy 会认为集群的成员在每个解析间隔期间都在变化，这将导致连接池驱逐、连接循环等。取而代之的是，使用逻辑 DNS，连接会保持存活，直到它们被循环。当与大规模 Web 服务交互时，这是所有可能的世界中最好的情况：异步/最终一致的 DNS 解析，长期维持的连接，以及转发路径中的零阻塞。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当传入的连接通过 iptable REDIRECT 或 TPROXY 目标或使用代理协议重定向到 Envoy 时，可以使用原始目标集群。在这些情况下，路由到原始目标集群的请求会被转发到重定向元数据所寻址的上游主机，而不需要任何明确的主机配置或上游主机发现。连接到上游主机的连接会被池化，当闲置时间超过 :ref:`cleanup_interval <envoy_v3_api_field_confi
```suggestion
当传入的连接通过 iptable REDIRECT 或 TPROXY 目标或使用代理协议重定向到 Envoy 时，可以使用原始目标集群。在这些情况下，路由到原始目标集群的请求会被转发到重定向元数据所寻址的上游主机，而不需要任何明确的主机配置或上游主机发现。连接到上游主机的连接会被池化，当闲置时间超过 :ref:`cleanup_interval <envoy_v3_api_field_config.cluster.v3.Cluster.cleanup_interval>` 时，未使用的主机会被清理，默认值为 5000ms。如果原始目的地不可用，则不创建上行连接。Envoy 也可以从 :ref:`HTTP 头 <arch_overview_load_balancing_types_original_destination_request_header>` 中获取原始目的地。原始目的地服务发现必须与原始目的地 :ref:`负载均衡 <arch_overview_load_balancing_types_original_destination>` 一起使用。
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +端点发现服务是一个 :ref:`基于 gRPC 或 REST-JSON API 的 xDS 管理服务器<config_overview_management_server>`，Envoy 用来通过它来获取集群成员。在 Envoy 的术语中，集群成员被称为“端点”。对于每个集群，Envoy 从发现服务中获取端点。EDS 是首选的服务发现机制，原因有以下几点：
```suggestion
*端点发现服务*是一个 :ref:`基于 gRPC 或 REST-JSON API 的 xDS 管理服务器<config_overview_management_server>`，Envoy 通过它来获取集群成员。在 Envoy 的术语中，集群成员被称为“端点”。对于每个集群，Envoy 从发现服务中获取端点。EDS 是首选的服务发现机制，原因有以下几点：
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +许多现有的 RPC 系统把服务发现当作一个完全一致的过程。为此，他们使用完全一致性的领袖选举后台存储，如 Zookeeper、etcd、Consul 等。我们的经验是，大规模运营这些后后存储是很痛苦的。
```suggestion
许多现有的 RPC 系统把服务发现当作一个完全一致的过程。为此，他们使用完全一致性的领导者选举的备份存储，如 Zookeeper、etcd、Consul 等。我们的经验是，大规模运营这些备份存储是很痛苦的。
```

话说 backing store这里我也不确定到底该如何翻译，感觉不是后台存储的意思。你再想想

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +* 当为上游集群配置健康检查时，Envoy 使用 2 x 2 矩阵来决定是否路由到主机：
```suggestion
* 当为上游集群配置健康检查时，Envoy 使用 2x2 矩阵来决定是否路由到主机：
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +  未发现, 执行路由, 不执行路由 / 移除
```suggestion
  未发现, 执行路由, 不执行路由/移除
```

2020-11-14 02:33 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +  Envoy **将路由** 到目标主机。这一点非常重要，因为设计中假设发现服务随时可能失败。如果一个主机在发现数据中不存在后仍然通过健康检查，Envoy 仍然会进行路由。虽然在这种情况下不可能增加新的主机，但现有的主机将继续正常运行。当发现服务再次正常运行时，数据最终会重新汇合。
```suggestion
  Envoy **将路由** 到目标主机。这一点非常重要，因为设计认为发现服务随时可能失败。如果一个主机在发现数据中不存在后仍然通过健康检查，Envoy 仍然会进行路由。虽然在这种情况下不可能增加新的主机，但现有的主机将继续正常运行。当发现服务再次正常运行时，数据最终会重新合并。
```

2020-11-14 02:34 UTC, addozhang commented
@webup 很棒的翻译，辛苦了。提了一些建议，以一定准确，麻烦再看一下。

2020-11-14 02:35 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
嗯 这个我下面也有提到，建议使用驱逐。参考 kubernets 中的 pod 驱逐

2020-11-14 03:34 UTC, webup commented
> @webup 很棒的翻译，辛苦了。提了一些建议，以一定准确，麻烦再看一下。

感谢，都修了～

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当在 Envoy :ref:`配置 <envoy_v3_api_msg_config.cluster.v3.Cluster>` 中定义了一个上游集群时，Envoy 需要知道如何解析集群的成员。这就是所谓的 *服务发现*。
这被称为 *服务发现*。

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
如果一个主机从结果中被删除，//或者：如果有主机从结果中删除，觉得还是这么说更顺畅一点：）

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +当使用严格 DNS 服务发现时，Envoy 将连续和异步解析指定的 DNS 目标。DNS 结果中的每个返回的 IP 地址将被视为上游集群中的一个显式主机。这意味着，如果查询返回三个 IP 地址，Envoy 将假设集群有三个主机，并且这三个主机都应该被负载均衡到。如果一个主机从结果中被删除，Envoy 会假设它不再存在，并将从任何现有的连接池中排出流量。因此，如果一个成功的 DNS 解析返回 0
Envoy 会认为它不再存在，并且会将它从所有的当前连接池中驱逐流量。 //所有会不会比任何更合适一点

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +如果多个 DNS 名解析到同一个 IP，健康检查将 *不共享*。这意味着，如果使用主动健康检查与解析到相同 IP 的 DNS 名，应注意：如果一个 IP 在 DNS 名之间多次重复，可能会对上游主机造成不必要的负载。
如果多个 DNS 名称解析到同一个 IP，健康检查将 *不共享*。这意味着，在使用解析到相同 IP 的 DNS 名称做主动健康检查时需要注意：如果一个 IP 在 DNS 名称之间多次重复，可能会对上游主机造成不必要的负载。//且，上一段也是翻译的名称：如果一个 DNS 名称多次解析到同一个 IP，这些 IP 将被去重。保持一致好一点吧。

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +如果启用了 :ref:`respect_dns_ttl <envoy_v3_api_field_config.cluster.v3.Cluster.respect_dns_ttl>`，则使用 DNS 记录 TTL 和 :ref:`dns_refresh_rate <envoy_v3_api_field_config.cluster.v3.Cluster.dns_refresh_rate>` 来控
最小值为 0，//0前面有空格，后面没有

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +DNS 解析会发出 :ref:`集群统计 <config_cluster_manager_cluster_stats>` 字段 *update_attempt*、*update_success* 和 *update_failure*。
DNS 解析会输出

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +逻辑 DNS 使用与严格 DNS 类似的异步解析机制。但是，逻辑 DNS 集群不是严格地取 DNS 查询的结果，并假设它们包含整个上游集群，而是只在 *需要启动新连接时* 才使用返回的第一个 IP 地址。因此，一个逻辑连接池可能包含到各种不同上游主机的物理连接。连接永远不会被耗尽，包括在 DNS 解析成功，返回 0 个主机的情况下。
但是，这种策略并非严格基于 DNS 的查询结果，

2020-11-14 04:45 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/service_discovery.rst
> +这种服务发现类型是必须通过 DNS 访问的大规模网络服务的最佳选择。这类服务通常使用轮询 DNS 来返回许多不同的 IP 地址。通常情况下，每次查询都会返回不同的结果。如果在这种情况下使用严格 DNS，Envoy 会认为集群的成员在每个解析间隔期间都在变化，这将导致消耗连接池、连接循环等。取而代之的是，使用逻辑 DNS，连接会保持存活，直到它们被循环。当与大规模 Web 服务交互时，这是所有可能
在与大型 Web 服务交互时，这几乎是所有可行策略中最好的方式

2020-11-14 07:43 UTC, webup commented
@scilla0531 感谢，都已修改～

2020-11-15 13:59 UTC, webup commented
@hzliangbin 你提的内容已经修改过了哦

2020-11-17 11:10 UTC, helight commented
LGTM
/approve

2020-11-18 00:47 UTC, addozhang commented
LGTM
/merged

2020-11-18 00:49 UTC, addozhang approved these changes
LGTM

2020-11-18 00:51 UTC, addozhang commented
/merged

2020-11-18 00:57 UTC, addozhang commented
/pushed

2020-11-18 01:02 UTC, merged