zh-translation: /intro/arch_overview/upstream/load_balancing/load_balancers.rst
cloudnativeto/envoy pull request #164
Opened 2020-11-14 09:21 UTC by shalk

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-11-14 10:08 UTC, scilla0531 reviewed
很棒的翻译，本次review主要检查了语法和规范。发现存在多处缺少空格和连续使用两个空格的问题。可以本地搜索下所有连续两个空格的地方，进行恰当替换。
关于空格的规范请见：https://github.com/cloudnativeto/envoy/blob/zh/docs/root/term.md 的格式约定部分

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +<config_cluster_manager_cluster_hc>` 活跃健康检查策略，集群所有成员都会被认为是健康的，除非通过:ref:`health_status <envoy_v3_api_field_config.endpoint.v3.LbEndpoint.health_status>`进行指定。
当过滤器需要获取到上游集群中主机的连接时，集群管理器将使用负载均衡策略来确定选择哪个主机。负载均衡策略是可拔查的，并且在 :ref:`配置<envoy_v3_api_msg_config.cluster.v3.Cluster>` 中以每个上游集群为基础进行指定。请注意，如果没有为集群 :ref:`配置
<config_cluster_manager_cluster_hc>` 活动的运行状况健康检查策略，则所有上游集群成员都认为是健康的，除非通过 :ref:`health_status <envoy_v3_api_field_config.endpoint.v3.LbEndpoint.health_status>` 进行指定。

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +* *所有权重全相同*：这是一个 O(1)  算法，通过:ref:`配置<envoy_v3_api_msg_config.cluster.v3.Cluster.LeastRequestLbConfig>`（默认为2）选择 N 个随机可用主机，选择这些主机中活跃请求最少的一台（`Mitzenmacher et al.
* *所有权重全相同*：这是一个 O(1)  算法，通过 :ref:`配置<envoy_v3_api_msg_config.cluster.v3.Cluster.LeastRequestLbConfig>`（默认为2）选择 N 个随机可用主机，//:ref 前面少了空格

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  <https://www.eecs.harvard.edu/~michaelm/postscripts/handbook2001.pdf>`_ 表明这个方法 只要 O(N) 次完全扫描)。 这个方法也被称为 P2C （两次选择的威力）。 P2C 负载均衡器的特点是最高请求量的主机，不会收到新的请求。这使得这台主机允许被放逐，直到它的请求量少于或等于其他主机。
<https://www.eecs.harvard.edu/~michaelm/postscripts/handbook2001.pdf>`_ 表明这个方法 只要 O(N) 次完全扫描)。这个方法也被称为 P2C（两次选择的威力）。 P2C 负载均衡器的特点是最高请求量的主机，不会收到新的请求。这使得这台主机允许被放逐，直到它的请求量少于或等于其他主机。//标点前后不需要空格

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  可以在运行时配置，默认为1。 它必须大于等于0.0。活跃请求偏差越大，更多的请求会会降低有效权重。
:ref:`活跃请求偏差 <envoy_v3_api_field_config.cluster.v3.Cluster.LeastRequestLbConfig.active_request_bias>`  可以在运行时配置，默认为 1。 它必须大于等于 0.0。活跃请求偏差越大，更多的请求会会降低有效权重。//本行多处存在缺少空格或者同时两个空格的问题。

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  例如，如果活跃请求偏差为 1.0，一个主机的权重为2 活跃请求量为 4 ，那么有效权重为 2 / (4 + 1)^1 = 0.4。算法给稳定状态提供了很好的均衡，但不适合负载极度不平衡。并且，和 P2C 不同，一台主机不会真的放逐，尽管它在一段时间内会收到更少的请求量。
例如，如果活跃请求偏差为 1.0，一个主机的权重为 2 活跃请求量为 4 ，那么有效权重为 2 / (4 + 1)^1 = 0.4。算法给稳定状态提供了很好的均衡，但不适合负载极度不平衡。并且，和 P2C 不同，一台主机不会真的放逐，尽管它在一段时间内会收到更少的请求量。

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +环状哈希负载均衡器实现了上游主机的一致性哈希。每个主机映射到一个圆环("ring") 上通过对它的地址进行哈希；每个请求路由到某个主机，通过哈希请求的某个属性，找到环上顺时针最近的主机。这个技术也被称为  `"Ketama" <https://github.com/RJ/ketama>`_ 哈希，像所有的基于哈希的负载均衡器一样，当协议有一个值可以哈希才有效。
环状哈希负载均衡器实现了上游主机的一致性哈希。每个主机映射到一个圆环("ring")上通过对它的地址进行哈希；每个请求路由到某个主机，通过哈希请求的某个属性，找到环上顺时针最近的主机。这个技术也被称为 `"Ketama" <https://github.com/RJ/ketama>`_ 哈希，像所有的基于哈希的负载均衡器一样，当协议有一个值可以哈希才有效。

2020-11-14 10:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +每个主机哈希并按照主机的权重对应环上一定比例的多个位置。例如，主机 A 权重为 1，主机 B 权重为 2，可能会有三个条目出现在环上：一个主机 A 的位置，两个主机 B 的位置。但是这了能并不满足 2:1 的比例划分圆环，因为计算的hash可能会让两个主机很接近；所以有必要乘数扩大每个主机的哈希数量，例如插入 100 个主机 A 的条目，200 个主机 B 的条目，这样更接近想要的分布。最佳实践
每个主机哈希并按照主机的权重对应环上一定比例的多个位置。例如，主机 A 权重为 1，主机 B 权重为 2，可能会有三个条目出现在环上：一个主机 A 的位置，两个主机 B 的位置。但是这了能并不满足 2:1 的比例划分圆环，因为计算的 hash 可能会让两个主机很接近；所以有必要乘数扩大每个主机的哈希数量，例如插入 100 个主机 A 的条目，200 个主机 B 的条目，这样更接近想要的分布。最佳实践是，指定 :ref:`环最小数量 <envoy_v3_api_field_config.cluster.v3.Cluster.RingHashLbConfig.minimum_ring_size>` 和 :ref:`环最大数量<envoy_v3_api_field_config.cluster.v3.Cluster.RingHashLbConfig.maximum_ring_size>`，并监控  :ref:`min_hashes_per_host and max_hashes_per_hostgauges<config_cluster_manager_cluster_stats_ring_hash_lb>` 来确保好的分布。如果环划分合适，增加或删除 N 个主机中的一个，只会影响 1/N 的请求。

2020-11-14 10:10 UTC, scilla0531 commented
@shalk 很棒的翻译，我本次review主要检查了语法和规范。发现存在多处缺少空格和连续使用两个空格的问题。可以本地搜索下所有连续两个空格的地方，进行恰当替换。
关于空格的规范请见：https://github.com/cloudnativeto/envoy/blob/zh/docs/root/term.md 的格式约定部分

2020-11-14 11:05 UTC, shalk commented
> 很棒的翻译，本次review主要检查了语法和规范。发现存在多处缺少空格和连续使用两个空格的问题。可以本地搜索下所有连续两个空格的地方，进行恰当替换。
> 关于空格的规范请见：https://github.com/cloudnativeto/envoy/blob/zh/docs/root/term.md 的格式约定部分

都替换了一下，避免了多空格；补充了必要的空格。

2020-11-14 11:36 UTC, vgbhfive reviewed
:ref:`活跃请求偏差<envoy_v3_api_field_config.cluster.v3.Cluster.LeastRequestLbConfig.active_request_bias>`  ，这一行前面多了一个空格。

2020-11-14 11:38 UTC, vgbhfive commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  可以在运行时配置，默认为1。它必须大于等于0.0。活跃请求偏差越大，更多的请求会降低有效权重。
31 行前面多了一个空格。

2020-11-14 12:39 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  可以在运行时配置，默认为1。它必须大于等于0.0。活跃请求偏差越大，更多的请求会降低有效权重。
已删除

2020-11-17 11:12 UTC, Miss-you commented
> 很棒的翻译，本次review主要检查了语法和规范。发现存在多处缺少空格和连续使用两个空格的问题。可以本地搜索下所有连续两个空格的地方，进行恰当替换。
> 关于空格的规范请见：https://github.com/cloudnativeto/envoy/blob/zh/docs/root/term.md 的格式约定部分

格式化可以考虑pangu插件，自动格式化

2020-11-17 12:32 UTC, scilla0531 commented
其实翻译的时候留意一下，空格的问题就顺手完成了。@majinghe 小马哥，空格的规范不用人工保证了么？目前是否可以做到上述提到的方式解决呢？

2020-11-17 12:52 UTC, shalk commented
> > 很棒的翻译，本次review主要检查了语法和规范。发现存在多处缺少空格和连续使用两个空格的问题。可以本地搜索下所有连续两个空格的地方，进行恰当替换。
> > 关于空格的规范请见：https://github.com/cloudnativeto/envoy/blob/zh/docs/root/term.md 的格式约定部分
> 
> 格式化可以考虑pangu插件，自动格式化

安装了一下vscode-pangu 很好用，一次就格式化好了，确实有个别疏漏。

就是有两个情况用pangu 会多产生空格，可能是rst的语法** 和 ``   和中间之间会加空格。

情况 1 ：
原文 
```
* *all weights equal*: 
```
格式化后
```
* * 所有权重全相同 *
```
情况 2：
```
:ref:` 
```

2020-11-26 15:07 UTC, hzliangbin requested changes
有两处错别字修改下。

2020-11-26 15:07 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +<config_cluster_manager_cluster_hc>` 活跃健康检查策略，集群所有成员都会被认为是健康的，除非通过:ref:`health_status <envoy_v3_api_field_config.endpoint.v3.LbEndpoint.health_status>`进行指定。
pluggable 可插拔

2020-11-26 15:07 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +* *所有权重不全相同*：如果两个或者更多的主机有不同的负载均衡权重，负载均衡器会进入另一种模式，使用基于权重的轮训调度，其中权重是根据主机被选中时的请求负载动态调节。
轮询

2020-11-27 03:53 UTC, hzliangbin commented
@shalk hi，感谢参与翻译，有两处错别字请核对修改下。

2020-11-27 05:09 UTC, shalk commented
> @shalk hi，感谢参与翻译，有两处错别字请核对修改下。

已修复

2020-11-27 08:42 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +构造表格的算法把每个主机按照它的权重以一定比例保存在表中，直到表格被完全填满。例如，主机 A 的权重为 1，主机 B 的权重为 2，那么主机 A 有 21846 个条目，主机 B 有 43691 个条目（总计65537 个条目）。这个算法尝试把每个主机放入表格中至少一次，无论主机权重和位置权重，这样在一些极端情况下，实际的比例和配置的权重可能不同。例如，主机的总数大于固定表格的大小，那么一些主机
（总计 65537 个条目）//数字前后空格
监控 :ref:`主机最小条目数 和 主机最大条目数 gauges <config_cluster_manager_cluster_stats_maglev_lb>`  //中文之间多余空格、gauges 翻译

2020-11-27 08:42 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +  :ref:`活跃请求偏差<envoy_v3_api_field_config.cluster.v3.Cluster.LeastRequestLbConfig.active_request_bias>`
:ref:`活跃请求偏差 <envoy_v3_api_field_config.cluster.v3.Cluster.LeastRequestLbConfig.active_request_bias>` //这个地方的约定是也加个空格，且这一行是换行了么？

2020-11-27 08:42 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>    可以在运行时配置，默认为1。它必须大于等于0.0。活跃请求偏差越大，更多的请求会降低有效权重。
默认为1。它必须大于等于0.0。//数字前后的空格

2020-11-27 08:42 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>    这种情况下被选中时主机的权重按照如下公式进行计算：`权重 = 负载均衡权重/ (活跃请求量 + 1)^活跃请求偏差`。
`权重 = 负载均衡权重/（活跃请求量 + 1）^活跃请求偏差`。

2020-11-27 08:42 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>  通常，当和环状哈希("ketama")算法比较时，Maglev 有更快的表格查询构建时间和主机选择时间(大概分别时 10 倍和 5 倍当使用一个 256K 的环时)。Maglev 的缺点是，它不是一个稳定的环状哈希。当主机移除时，移动的键值更多（模拟时接近双倍的键值会被移动）。这样来说，许多应用包括 Redis，Maglev 对环状哈希的替换有极大的落差。高级的读者可以用 :repo:`这个基准
当和环状哈希("ketama")   //使用中文符号，其他地方同样
当和环状哈希（“ketama”）
对于包括 Redis 在内的许多应用程序而言，Maglve 很可能会取代环形哈希技术   ，或上等替代品 。

2020-11-27 10:12 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +构造表格的算法把每个主机按照它的权重以一定比例保存在表中，直到表格被完全填满。例如，主机 A 的权重为 1，主机 B 的权重为 2，那么主机 A 有 21846 个条目，主机 B 有 43691 个条目（总计65537 个条目）。这个算法尝试把每个主机放入表格中至少一次，无论主机权重和位置权重，这样在一些极端情况下，实际的比例和配置的权重可能不同。例如，主机的总数大于固定表格的大小，那么一些主机
你好像review 旧的文档。。。

2020-11-27 10:19 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +构造表格的算法把每个主机按照它的权重以一定比例保存在表中，直到表格被完全填满。例如，主机 A 的权重为 1，主机 B 的权重为 2，那么主机 A 有 21846 个条目，主机 B 有 43691 个条目（总计65537 个条目）。这个算法尝试把每个主机放入表格中至少一次，无论主机权重和位置权重，这样在一些极端情况下，实际的比例和配置的权重可能不同。例如，主机的总数大于固定表格的大小，那么一些主机
https://github.com/cloudnativeto/envoy/pull/164/files

2020-11-28 01:47 UTC, majinghe commented
@shalk 有一些新的 comment。看一下，处理一下。

2020-11-28 02:11 UTC, helight commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>  通常，当和环状哈希("ketama")算法比较时，Maglev 有更快的表格查询构建时间和主机选择时间(大概分别时 10 倍和 5 倍当使用一个 256K 的环时)。Maglev 的缺点是，它不是一个稳定的环状哈希。当主机移除时，移动的键值更多（模拟时接近双倍的键值会被移动）。这样来说，许多应用包括 Redis，Maglev 对环状哈希的替换有极大的落差。高级的读者可以用 :repo:`这个基准
主机 B 有 43691 个条目（总计 65537 个条目）

这里还有一个空格

2020-11-28 05:07 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
当过滤器需要获取到上游集群主机的连接时，集群管理器将使用负载均衡策略来确定选择哪台主机。负载均衡策略是可拔插的，并且在 :ref:`配置 <envoy_v3_api_msg_config.cluster.v3.Cluster>` 中以每个上游集群为基础进行指定。请注意，如果没有为集群 :ref:`配置 <config_cluster_manager_cluster_hc>` 活动的运行状况健康检查策略，则所有上游集群成员都认为是健康的，除非通过 :ref:`health_status <envoy_v3_api_field_config.endpoint.v3.LbEndpoint.health_status>` 进行指定。

2020-11-28 05:07 UTC, scilla0531 commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>  * *所有权重全相同*：这是一个 O(1)  算法，通过 :ref:`配置 <envoy_v3_api_msg_config.cluster.v3.Cluster.LeastRequestLbConfig>` （默认为 2）选择 N 个随机可用主机，选择这些主机中活跃请求最少的一台（`Mitzenmacher et al.<https://www.eecs.harvard.edu/~michae
这是一个 O(1) 算法，//连续两个空格

2020-11-28 13:10 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
已合并到单行

2020-11-28 13:11 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
>  * *所有权重全相同*：这是一个 O(1)  算法，通过 :ref:`配置 <envoy_v3_api_msg_config.cluster.v3.Cluster.LeastRequestLbConfig>` （默认为 2）选择 N 个随机可用主机，选择这些主机中活跃请求最少的一台（`Mitzenmacher et al.<https://www.eecs.harvard.edu/~michae
fixed

2020-11-30 10:21 UTC, shalk commented
@scilla0531  已修复，再看看

2020-11-30 12:00 UTC, scilla0531 commented
/LGTM

2020-12-01 02:22 UTC, hzliangbin approved these changes

2020-12-01 02:23 UTC, hzliangbin commented
/LGTM

2020-12-04 02:54 UTC, helight commented on docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
> +构造表格的算法把每个主机按照它的权重以一定比例保存在表中，直到表格被完全填满。例如，主机 A 的权重为 1，主机 B 的权重为 2，那么主机 A 有 21846 个条目，主机 B 有 43691 个条目（总计 65537 个条目）。这个算法尝试把每个主机放入表格中至少一次，无论主机权重和位置权重，这样在一些极端情况下，实际的比例和配置的权重可能不同。例如，主机的总数大于固定表格的大小，那么一些主
```suggestion
构造表格的算法把每个主机按照它的权重以一定比例保存在表中，直到表格被完全填满。例如，主机 A 的权重为 1，主机 B 的权重为 2，那么主机 A 有 21846 个条目，主机 B 有 43691 个条目（总计 65537 个条目）。这个算法尝试把每个主机放入表格中至少一次，无论主机权重和位置权重，这样在一些极端情况下，实际的比例和配置的权重可能不同。例如，主机的总数大于固定表格的大小，那么一些主机获得了一个条目，其余主机无论权重是多少，它的条目数是 0。最佳实践是，监控 :ref:`主机最小条目数和主机最大条目数 gauges <config_cluster_manager_cluster_stats_maglev_lb>` 确保没有主机被表示不足或缺失。
```

2020-12-04 07:12 UTC, helight commented
LGTM

2020-12-04 07:12 UTC, merged