zh-translation: docs/root/intro/arch_overview/security/ext_authz_filt…
cloudnativeto/envoy pull request #165
Opened 2020-11-14 09:39 UTC by scilla0531

…er.rst

ref: https://github.com/cloudnativeto/envoy/issues/27

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-11-14 12:55 UTC, shalk reviewed
fail open 是专业术语，建议翻译为 故障打开

2020-11-14 12:55 UTC, shalk commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +外部授权服务群集可以是静态配置的，也可以是通过 :ref:`集群服务发现 <config_cluster_manager_cds>` 配置的。如果在请求到达时外部服务不可用，则该请求是否被授权由 :ref:`网络过滤器 <envoy_v3_api_msg_extensions.filters.network.ext_authz.v3.ExtAuthz>` 或 :ref:`HTTP 过滤器 <en
fail open 是专业术语，建议翻译为 故障打开，参考 [这里](https://hongwangle.com/terms-definition/visibility-terms-analysis/fail-open/)

2020-11-14 13:04 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +外部授权服务群集可以是静态配置的，也可以是通过 :ref:`集群服务发现 <config_cluster_manager_cds>` 配置的。如果在请求到达时外部服务不可用，则该请求是否被授权由 :ref:`网络过滤器 <envoy_v3_api_msg_extensions.filters.network.ext_authz.v3.ExtAuthz>` 或 :ref:`HTTP 过滤器 <en
好哒，多谢多谢。还粘贴了链接，太赞了！

2020-11-17 06:34 UTC, Miss-you requested changes
翻译的很好~赞👍

2020-11-17 06:34 UTC, Miss-you commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +外部授权过滤器调用授权服务以检查传入请求是否被授权。过滤器可以配置为 :ref:`网络过滤器 <config_network_filters_ext_authz>` 或 :ref:`HTTP 过滤器 <config_http_filters_ext_authz>` 或两者。如果该请求被网络过滤器视为未被授权，则连接将被关闭。如果该请求在 HTTP 过滤器中被视为未被授权，则该请求将被 403（禁
或两者
-》
或两者同时生效
或同时配置两者

2020-11-17 06:34 UTC, Miss-you commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +外部授权过滤器调用授权服务以检查传入请求是否被授权。过滤器可以配置为 :ref:`网络过滤器 <config_network_filters_ext_authz>` 或 :ref:`HTTP 过滤器 <config_http_filters_ext_authz>` 或两者。如果该请求被网络过滤器视为未被授权，则连接将被关闭。如果该请求在 HTTP 过滤器中被视为未被授权，则该请求将被 403（禁
Network filter configuration
网络层过滤器？
TCP 过滤器？
网络过滤器容易产生误解

2020-11-17 06:34 UTC, Miss-you commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +外部授权服务群集可以是静态配置的，也可以是通过 :ref:`集群服务发现 <config_cluster_manager_cds>` 配置的。如果在请求到达时外部服务不可用，则该请求是否被授权由 :ref:`网络过滤器 <envoy_v3_api_msg_extensions.filters.network.ext_authz.v3.ExtAuthz>` 或 :ref:`HTTP 过滤器 <en
该请求将被允许
-》
该请求将被放通/放行

2020-11-17 06:34 UTC, Miss-you commented on docs/root/intro/arch_overview/security/ext_authz_filter.rst
> +通信的上下文使用此处列出的服务定义传递到外部授权服务。
通信的上下文使用此处列出的服务定义传递到外部授权服务。
-》
与外部授权服务通信的上下文使用此处的定义

2020-11-17 07:38 UTC, scilla0531 commented
@shalk @Miss-you 感谢review，修改已经提交，请查阅

2020-11-24 02:26 UTC, merged