zh-translation: /intro/arch_overview/other_features/global_rate_limiting.rst
cloudnativeto/envoy pull request #169
Opened 2020-11-15 11:54 UTC by alandtsang

#56

2020-11-17 06:00 UTC, Miss-you commented
速率限制 麻烦都改为限流

2020-11-17 06:16 UTC, Miss-you requested changes
请参考review意见修改

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +全局速率限制
全局限流
或者
分布式限流

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
断路
->
断路器

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
通常在控制分布式系统中的吞吐量方面非常有效
-》
通常在控制分布式系统中的吞吐量非常有效

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
通常
-》
在大多数情况下

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
但有时效果不是很好，需要全局速率限制。
-》
但有时它的效果不是很好，这时候便需要全局限流/分布式限流

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
（例如，到数据库服务器的连接/请求）
-》
（例如，发送给数据库服务器的连接/请求）

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
如果目标主机已备份
->
若目标主机成为备机

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
则下游主机将压垮上游群集
-》
则下游主机将压垮上游集群

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
使系统在平常的请求模式下可以正常运行
-》
使得系统可以平稳运行

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
but still prevent cascading failure when the system starts
to fail.
同时，当系统开始出现故障时，仍然可以防止级联故障。

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
Global rate limiting is a good solution for this case.
对于这种情况，全局限流是一个很好的解决方案。

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +速率限制服务 :ref:`配置 <config_rate_limit_service>`。
速率限制服务 优化下

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +Envoy 直接与全局 gRPC 速率限制服务集成。尽管可以使用任何实现定义 RPC/IDL 协议的服务，但 Lyft 提供了 Go 编写的使用 Redis 后端的 `参考实现 <https://github.com/lyft/ratelimit>`_ 。Envoy 的速率限制具有以下功能：
Envoy可以直接与全局gRPC限流服务集成
Envoy integrates directly with a global gRPC rate limiting service.

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +Envoy 直接与全局 gRPC 速率限制服务集成。尽管可以使用任何实现定义 RPC/IDL 协议的服务，但 Lyft 提供了 Go 编写的使用 Redis 后端的 `参考实现 <https://github.com/lyft/ratelimit>`_ 。Envoy 的速率限制具有以下功能：
尽管可以使用任何实现定义 RPC/IDL 协议的服务
-》
尽管Envoy可以使用任何实现定义 RPC/IDL 协议的服务

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +* **网络级别速率限制过滤器**：Envoy 在安装了过滤器的 listener 上的每个新连接调用速率限制服务。该配置指定了要设置速率限制的特定域和描述符。最终会限制每秒经过 listener 连接的速率。:ref:`配置参考
网络级限流过滤器
Network level rate limit filter

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +* **网络级别速率限制过滤器**：Envoy 在安装了过滤器的 listener 上的每个新连接调用速率限制服务。该配置指定了要设置速率限制的特定域和描述符。最终会限制每秒经过 listener 连接的速率。:ref:`配置参考
Configuration reference
参考配置

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +* **网络级别速率限制过滤器**：Envoy 在安装了过滤器的 listener 上的每个新连接调用速率限制服务。该配置指定了要设置速率限制的特定域和描述符。最终会限制每秒经过 listener 连接的速率。:ref:`配置参考
最终会限制每秒经过 listener 连接的速率
连接速度这个词，应该用术语`并发连接`

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +速率限制服务 :ref:`配置 <config_rate_limit_service>`。
Envoy将会对配置了该过滤器的监听器上的每一个新请求调用限流服务

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +速率限制服务 :ref:`配置 <config_rate_limit_service>`。
所有向目标上游集群发出的请求以及从源集群向目标集群发出的所有请求都可以进行速率限制。

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +请注意，Envoy 还支持 :ref:`本地速率限制 <config_network_filters_local_rate_limit>`。本地速率限制可以与全局速率限制结合使用，以减少全局速率限制服务的负载。例如，本地令牌桶速率限制可以承受非常大的突发负载，否则可能会压垮全局速率限制服务。因此，速率限制分为两个阶段。在细粒度全局限制完成工作之前，由令牌桶限制执行初始粗粒度限制。
请注意
-》
注意

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +请注意，Envoy 还支持 :ref:`本地速率限制 <config_network_filters_local_rate_limit>`。本地速率限制可以与全局速率限制结合使用，以减少全局速率限制服务的负载。例如，本地令牌桶速率限制可以承受非常大的突发负载，否则可能会压垮全局速率限制服务。因此，速率限制分为两个阶段。在细粒度全局限制完成工作之前，由令牌桶限制执行初始粗粒度限制。
本地速率限制
-》
单机限流

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +请注意，Envoy 还支持 :ref:`本地速率限制 <config_network_filters_local_rate_limit>`。本地速率限制可以与全局速率限制结合使用，以减少全局速率限制服务的负载。例如，本地令牌桶速率限制可以承受非常大的突发负载，否则可能会压垮全局速率限制服务。因此，速率限制分为两个阶段。在细粒度全局限制完成工作之前，由令牌桶限制执行初始粗粒度限制。
全局速率限制
-》
全局限流

2020-11-17 06:16 UTC, Miss-you commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +请注意，Envoy 还支持 :ref:`本地速率限制 <config_network_filters_local_rate_limit>`。本地速率限制可以与全局速率限制结合使用，以减少全局速率限制服务的负载。例如，本地令牌桶速率限制可以承受非常大的突发负载，否则可能会压垮全局速率限制服务。因此，速率限制分为两个阶段。在细粒度全局限制完成工作之前，由令牌桶限制执行初始粗粒度限制。
在细粒度全局限制完成工作之前，由令牌桶限制执行初始粗粒度限制。
-》
全局限流进行细粒度的分布式限流调控，单机限流通过令牌桶的方式进行粗粒度的限流。

2020-11-17 06:35 UTC, Miss-you commented
评论中的单机限流建议改为本地限流

2020-11-17 10:18 UTC, Ayden-Franklin commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +尽管分布式 :ref:`断路 <arch_overview_circuit_break>` 通常在控制分布式系统中的吞吐量方面非常有效，但有时效果不是很好，需要全局速率限制。最常见的情况是当大量主机转发到少量主机并且平均请求延迟很短时（例如，到数据库服务器的连接/请求）。如果目标主机已备份，则下游主机将压垮上游群集。在这种情况下，很难在每个下游主机上配置足够严格的断路限制，使系统在平常的请求模式
断路器要改为熔断器，这份文章中术语用的是熔断器，我也是开始使用了断路器，后来看到术语列表中已经指定了使用熔断器。

2020-11-19 15:56 UTC, alandtsang commented
@Miss-you @Ayden-Franklin  已修正

2020-11-25 05:31 UTC, majinghe commented on docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
> +Envoy 可以直接与全局 gRPC 限流服务集成。尽管 Envoy 可以使用任何实现定义 RPC/IDL 协议的服务，但 Lyft 提供了 Go 编写的使用 Redis 后端的 `参考实现 <https://github.com/lyft/ratelimit>`_ 。Envoy 的限流具有以下功能：
```suggestion
Envoy 可以直接与全局 gRPC 限流服务集成。尽管可以使用任何实现定义 RPC/IDL 协议的服务，但 Lyft 提供了 Go 编写的使用 Redis 后端的 `参考实现 <https://github.com/lyft/ratelimit>`_ 。Envoy 的限流具有以下功能：
```

2020-11-25 05:32 UTC, majinghe commented
@alandtsang  添加了一个 comment，参考一下，是否需要修改。

2020-11-25 12:24 UTC, alandtsang commented
@majinghe 看了前后的语义，主语确实应该是 Lfyt，已修复

2020-11-28 01:46 UTC, majinghe commented
/LGTM

2020-11-28 01:46 UTC, majinghe commented
@Miss-you  yousa 看一下这个还有问题没。

2020-11-28 02:22 UTC, helight commented
LGTM
/approve

2020-11-28 02:22 UTC, merged