zh-translation: /intro/arch_overview/listeners/listeners.rst
cloudnativeto/envoy pull request #171
Opened 2020-11-15 13:05 UTC by vgbhfive

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes: /intro/arch_overview/listeners/listeners.rst
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] #50
[Optional Deprecated:]

2020-11-16 05:42 UTC, majinghe commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +当监听器上接收到新连接时，会选择适当的筛选器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
```suggestion
当监听器上接收到新连接时，会选择适当的过滤器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
```

2020-11-16 05:42 UTC, majinghe commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +<arch_overview_http_conn_man>`、MongoDB :ref:`嗅探 <arch_overview_mongo>`、原始 :ref:`TCP 代理<arch_overview_tcp_proxy>` 等）。
```suggestion
<arch_overview_http_conn_man>`、MongoDB :ref:`嗅探 <arch_overview_mongo>`、原始 :ref:`TCP 代理 <arch_overview_tcp_proxy>` 等）。
```

2020-11-16 05:42 UTC, majinghe commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
```suggestion
这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续过滤器或集群如何处理连接。
```

2020-11-16 05:42 UTC, majinghe commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +监听器 :ref:`配置 <config_listeners>`。
```suggestion
监听器 :ref:`配置 <config_listeners>` 。
```

2020-11-16 05:43 UTC, majinghe commented
@vgbhfive  添加了一下comment，仅供参考。

2020-11-16 06:10 UTC, Miss-you requested changes, later dismissed
麻烦参考review意见修改

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +Envoy 配置支持单个进程中配置任意数量的监听器。
这里是不是将多行文字变成一行比较好？

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +Envoy 配置支持单个进程中配置任意数量的监听器。
Envoy 配置支持单个进程中配置任意数量的监听器。
->
Envoy 支持单个进程中配置任意数量的监听器。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +通常情况下，为我们建议在每台机器上仅部署一个 Envoy，而不具体配置监听器的数量。
Generally we
recommend running a single Envoy per machine regardless of the number of configured listeners.
这段翻译的不好，它的本意是部署时部署envoy的数量跟监听器数量无关，建议每个机器部署一个Envoy即可

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这使得操作会更加的简单，而且统计数据来源单一。
This
allows for easier operation and a single source of statistics.
使得运维更简便，且每台机器只有一个监控数据来源

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +每个监听器都独立配置了多个 :ref:`过滤器链 <envoy_v3_api_msg_config.listener.v3.FilterChain>`，其中根据其 :ref:`匹配条件 <envoy_v3_api_msg_config.listener.v3.FilterChainMatch>` 选择单个过滤器链。
选择单个过滤器链。
-》
选择某个过滤器链。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +单个过滤器链由一个或多个网络层(L3/L4) :ref:`过滤器 <arch_overview_network_filters>` 组成。
单个过滤器链
->
一个独立的过滤器链

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +当监听器上接收到新连接时，会选择适当的筛选器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
当监听器上接收到新连接时
->
当监听器上监听到新连接时

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +当监听器上接收到新连接时，会选择适当的筛选器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
会选择适当的筛选器链
-》
会选择适当的过滤器链

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
筛选-》过滤

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +当监听器上接收到新连接时，会选择适当的筛选器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
接着实例化配置的本地筛选器堆栈和处理后续事件。
-》
接着实例化配置的本地过滤器堆栈和处理后续事件。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +当监听器上接收到新连接时，会选择适当的筛选器链，接着实例化配置的本地筛选器堆栈和处理后续事件。
接着实例化配置的本地筛选器堆栈和处理后续事件。
-》
接着实例化本地过滤器堆栈配置以及处理后续事件。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +通用监听器体系结构通常用于执行绝大多数不同的代理任务，例如 Envoy 用于（ :ref:`限速 <arch_overview_global_rate_limit>`、:ref:`TLS 客户端身份验证 <arch_overview_ssl_auth_filter>`、:ref:`HTTP 连接管理
通用监听器体系结构
->
通用监听器系统架构
通用监听器架构
通用监听器框架

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +通用监听器体系结构通常用于执行绝大多数不同的代理任务，例如 Envoy 用于（ :ref:`限速 <arch_overview_global_rate_limit>`、:ref:`TLS 客户端身份验证 <arch_overview_ssl_auth_filter>`、:ref:`HTTP 连接管理
通常用于执行绝大多数不同的代理任务
->
通常用于处理绝大多数不同的代理任务

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +通用监听器体系结构通常用于执行绝大多数不同的代理任务，例如 Envoy 用于（ :ref:`限速 <arch_overview_global_rate_limit>`、:ref:`TLS 客户端身份验证 <arch_overview_ssl_auth_filter>`、:ref:`HTTP 连接管理
绝大多数不同的代理任务
-》
各不相同的代理任务/多种多样的代理任务

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
还可以选择配置，这段话可能要再想想

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
这些过滤器在网络层过滤器之前处理
-》
这些过滤器将会在网络层过滤器之前进行处理

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
并且有机会去操作连接元数据
-》
并且有机会去修改连接元数据

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这些过滤器在网络层过滤器之前处理，并且有机会去操作连接元数据，这样通常是为了影响后续筛选器或集群如何处理连接。
为了影响
-》
为了控制

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +Envoy 还支持 UDP 监听器，特别是 :ref:`UDP 监听过滤器 <config_udp_listener_filters>` 。
specifically :ref:`UDP listener filters
这段还需要优化下

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +Envoy 还支持 UDP 监听器，特别是 :ref:`UDP 监听过滤器 <config_udp_listener_filters>` 。
Envoy 还支持 UDP 监听器和UDP监听过滤器

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +UDP 监听过滤器会为每个工作线程实例化一次，并且对该工作线程是全局的。
每个工作线程都会实例化 UDP 监听过滤器，而且 UDP 监听过滤器对于工作线程来讲是全局可见的。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +每个监听过滤器处理由工作线程监听的端口接收到的 UDP 数据报文。
这段话非常非常别扭……

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +实际上，UDP 监听器配置有一个 ``SO_REUSEPORT`` 内核选项，这将导致内核会一致性地将每个 UDP 四个元组分配给同一个工作线程。
实际上，UDP 监听器若打开了 ``SO_REUSEPORT`` 内核选项，这将导致内核会将属于同一个 UDP 四个元组的UDP 报文分配给同一个工作线程。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这就允许 UDP 监听过滤器在需要时可以使用 "session"。
这边是所谓的 UDP 流的会话保持。

2020-11-16 06:10 UTC, Miss-you commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这个功能的一个内置示例就是 :ref:`UDP 代理 <config_udp_listener_filters_udp_proxy>` 监听过滤器。
你可以使用这个配置 xxx 来打开 UDP 监听器的会话保持功能

2020-11-17 13:40 UTC, vgbhfive commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +这就允许 UDP 监听过滤器在需要时可以使用 "session"。
已修复！

2020-11-27 14:08 UTC, majinghe commented on docs/root/intro/arch_overview/listeners/listeners.rst
> +Envoy 同时支持 TCP 和 UDP 监听器。
这个是一段话，中文也应该是一段。

2020-11-27 14:10 UTC, majinghe commented
@vgbhfive  英文是一段，中文也应该是一段，感觉分开了呢。看看处理一下。

2020-11-27 14:27 UTC, majinghe commented
/LGTM

2020-11-27 14:27 UTC, merged