zh-translation: /intro/arch_overview/upstream/load_balancing/original_dst.rst
cloudnativeto/envoy pull request #172
Opened 2020-11-15 14:41 UTC by webup

ref: https://github.com/cloudnativeto/envoy/issues/63

2020-11-15 16:08 UTC, shalk reviewed
看了一下，很棒

2020-11-15 16:08 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +这是一种专用的负载均衡器，只能用于 :ref:`一个原始目标集群 <arch_overview_service_discovery_types_original_destination>`。上游主机是根据下游连接元数据选择的，即连接被打开到与连接重定向到 Envoy 之前传入与连接的目标地址相同的地址。新的目的地址由负载均衡器按需添加到集群中，集群 :ref:`定期 <envoy_v3_api_
original destination  目标规则 原始目的地， 这里建议保持一致  一个原始目的地集群

2020-11-15 16:08 UTC, shalk commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +这是一种专用的负载均衡器，只能用于 :ref:`一个原始目标集群 <arch_overview_service_discovery_types_original_destination>`。上游主机是根据下游连接元数据选择的，即连接被打开到与连接重定向到 Envoy 之前传入与连接的目标地址相同的地址。新的目的地址由负载均衡器按需添加到集群中，集群 :ref:`定期 <envoy_v3_api_
> 即连接被打开到与连接重定向到 Envoy 之前传入与连接的目标地址相同的地址。
调整了一下:
connections are opened to **the same** **address** **as**  **the**	
destination **address** of the incoming connection **was** before the connection was redirected to	
Envoy

也就是，连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同。

2020-11-15 18:00 UTC, Miss-you commented
我看了下这段英文，给我的感觉是
Original destination是会话保持负载均衡算法……大家觉得呢？

2020-11-15 18:03 UTC, Miss-you reviewed
> 我看了下这段英文，给我的感觉是
> Original destination是会话保持负载均衡算法……大家觉得呢？

又重新理解了一下，看起来像是专门给mesh使用的一种负载均衡算法

2020-11-15 18:03 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> -Original destination
这段不翻译是不是比较好
或者叫 ORIGINAL_DST

2020-11-16 00:14 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> -Original destination
原来的 1.7 翻译也是翻了的，也是原始目的地

2020-11-16 03:48 UTC, shalk commented
/LGTM

2020-11-16 05:13 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> -Original destination
> 原来的 1.7 翻译也是翻了的，也是原始目的地

ok

2020-11-16 05:20 UTC, Miss-you requested changes
请参考review意见修改

2020-11-16 05:20 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +这是一种专用的负载均衡器，只能用于 :ref:`一个原始目的地集群 <arch_overview_service_discovery_types_original_destination>`。上游主机是根据下游连接元数据选择的，也就是，连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同。新的目的地址由负载均衡器按需添加到集群中，集群 :ref:`定期 <envoy_v3_a
也就是，连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同。
这一段翻译的不太好，需要再优化下。
连接不应该被翻译成被打开吧，比如连接被负载均衡到/分配到xxx 与之前相同的地址，大概类似于这样

2020-11-16 05:20 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +Envoy 也可以从一个名为 :ref:`x-envoy-original-dst-host <config_http_conn_man_headers_x-envoy-original-dst-host>` 的 HTTP 请求头中获取原始目的地。请注意，在这个头中应该传递完全解析的 IP 地址。例如，如果一个请求被路由到一个 IP 地址为 10.195.16.237、端口为 8888 的主机，
在这个头中
->
在这个请求头中

2020-11-16 09:44 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +Envoy 也可以从一个名为 :ref:`x-envoy-original-dst-host <config_http_conn_man_headers_x-envoy-original-dst-host>` 的 HTTP 请求头中获取原始目的地。请注意，在这个头中应该传递完全解析的 IP 地址。例如，如果一个请求被路由到一个 IP 地址为 10.195.16.237、端口为 8888 的主机，
这个OK

2020-11-16 09:45 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +这是一种专用的负载均衡器，只能用于 :ref:`一个原始目的地集群 <arch_overview_service_discovery_types_original_destination>`。上游主机是根据下游连接元数据选择的，也就是，连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同。新的目的地址由负载均衡器按需添加到集群中，集群 :ref:`定期 <envoy_v3_a
这个是不好翻，请提供一些建议吧，这句已经翻了三版了

2020-11-21 12:45 UTC, addozhang reviewed
LGTM

2020-11-21 12:45 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/load_balancing/original_dst.rst
> +这是一种专用的负载均衡器，只能用于 :ref:`一个原始目的地集群 <arch_overview_service_discovery_types_original_destination>`。上游主机是根据下游连接元数据选择的，也就是，连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同。新的目的地址由负载均衡器按需添加到集群中，集群 :ref:`定期 <envoy_v3_a
@webup @Miss-you 我觉得原来的翻译没有问题。“连接被打开到的地址，与传入连接被重定向到 Envoy 之前的目标地址相同”

Envoy 是一个代理的角色，接受重定向过来的请求，将原来请求的目的地址作为代理的目的地址。

2020-11-25 02:52 UTC, Miss-you approved these changes
LGTM

2020-11-25 02:52 UTC, merged