zh-translation: /intro/arch_overview/upstream/load_balancing/overprovisioning.rst
cloudnativeto/envoy pull request #174
Opened 2020-11-15 15:26 UTC by webup

ref: https://github.com/cloudnativeto/envoy/issues/65

2020-11-15 17:54 UTC, Miss-you commented
参考codereview修改下，谢谢

2020-11-15 17:54 UTC, Miss-you requested changes

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
超额供给的百分比值
-> 
百分比

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
可用主机 -> 有效host    可用host

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
until the fraction of available hosts multiplied by the overprovisioning factor drops
below 100.
在可用host与过载系数的乘积低于100之前

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数
过载系数

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
(in percentage, which means 140%)
->
它的单位是百分比，即 140%

2020-11-15 17:54 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
locality 翻译成 本机 比较好

2020-11-16 00:20 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数
确定这个是标准的说法吗，和之前保持统一，要改就要都改了

2020-11-16 00:20 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
> 可用主机 -> 有效host 可用host

host 肯定是需要翻译的，都是翻译过来的

2020-11-16 00:21 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
> (in percentage, which means 140%)
> ->
> 它的单位是百分比，即 140%

这个两种都差不多，不改了

2020-11-16 00:22 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
> locality 翻译成 本机 比较好

这个也是和前面统一，需要再斟酌

2020-11-17 06:22 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
> > 可用主机 -> 有效host 可用host
> 
> host 肯定是需要翻译的，都是翻译过来的

ok

2020-11-26 03:37 UTC, mars-zhangcong commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数
个人感觉应该翻译为：过量供给因数 或 超额供给因数，Overprovisioning Factor,  Factor 是因数

2020-11-26 03:48 UTC, majinghe commented
@webup  海立，统一了一下 Overprovisioning Factor 翻译成 超额供给因数。麻烦你在这个文章中，通篇改一下。

2020-11-26 03:53 UTC, majinghe commented on docs/root/intro/arch_overview/upstream/load_balancing/overprovisioning.rst
> +超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机的份数乘以超额供给系数降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即
```suggestion
超额供给系数是流量在优先级和区域纬度被 :ref:`超额供给的百分比值 <envoy_v3_api_field_config.endpoint.v3.ClusterLoadAssignment.Policy.overprovisioning_factor>`。在可用主机数量和超额供给因数的乘积降至 100 以下之前，Envoy 不会认为某个优先级或区域不可用。默认值是 140（以百分比为单位，即 140%），因此在可用端点的百分比低于 72% 之前，优先级或区域不会被视为不可用。
```

2020-11-26 04:17 UTC, webup commented
> @webup 海立，统一了一下 Overprovisioning Factor 翻译成 超额供给因数。麻烦你在这个文章中，通篇改一下。

好的，已统一修改～

2020-11-26 06:02 UTC, majinghe commented
/LGTM

2020-11-26 06:02 UTC, merged