zh-translation: /intro/arch_overview/upstream/load_balancing/priority.rst
cloudnativeto/envoy pull request #186
Opened 2020-11-21 08:59 UTC by webup

ref: https://github.com/cloudnativeto/envoy/issues/29

2020-11-23 01:03 UTC, addozhang reviewed
很棒的翻译。

2020-11-23 01:03 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +  为了使负载分配算法和归一化总健康计算能够正常工作，每个优先级必须能够处理（100% * 超额供给系数）的流量。Envoy 假设一个 100% 健康的 P=1 可以完全取代一个不健康的 P=0，等等。如果 P=0 有 10 台主机，但 P=1 只有 2 台主机，这个假设可能就不成立了。
```suggestion
  为了使负载分配算法和归一化总健康计算能够正常工作，每个优先级必须能够处理（100% * 超额供给系数）的流量：Envoy 假设一个 100% 健康的 P=1 可以完全取代一个不健康的 P=0，等等。如果 P=0 有 10 台主机，但 P=1 只有 2 台主机，这个假设可能就不成立了。
```

2020-11-23 01:03 UTC, addozhang commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +健康分数代表了一个级别当前处理流量的能力，其中考虑到了该级别最初的超额配置，以及当前有多少端点是不健康的。因此，如果所有级别的健康分数之和小于 100，那么 Envoy 认为没有足够的健康端点来完全处理流量。这个总和称为‘归一化总健康度“。当归一化总健康度降到 100 以下时，将各层的健康度分数归一化到该 100 以下的总分后再分配流量。如：健康度为 {20，30}（得出归一化的总健康度为 50
```suggestion
在考虑到了该级别最初的超额配置以及当前有多少端点是不健康的的之后，健康分数代表了该级别当前处理流量的能力。因此，如果所有级别的健康分数之和小于 100，那么 Envoy 认为没有足够的健康端点来完全处理流量。这个总和称为‘归一化总健康度“。当归一化总健康度降到 100 以下时，将各层的健康度分数归一化到该 100 以下的总分后再分配流量。如：健康度为 {20，30}（得出归一化的总健康度为 50）将被归一化，并导致 {40%，60%} 的流量优先负载。
```
只是建议，感觉会更流畅一些。第一句里有个“After”

2020-11-24 05:59 UTC, majinghe commented
非常棒的翻译 /LGTM。

2020-11-24 05:59 UTC, majinghe commented
@webup   晓辉给你加了些comment。你参考一下。

2020-11-24 08:14 UTC, webup commented
> @webup 晓辉给你加了些comment。你参考一下。

感谢，已修改 🙏

2020-11-24 11:02 UTC, Miss-you requested changes
麻烦参考下review意见

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +在负载均衡过程中，Envoy 一般只会考虑处于最高优先级的主机。对于每个 EDS :ref:`LocalityLbEndpoints <envoy_v3_api_msg_config.endpoint.v3.LocalityLbEndpoints>` 还可以指定一个可选的优先级。当最高优先级（P=0）的端点是健康的，所有的流量将流转在该优先级的端点上。当最高优先级的端点变得不健康时，流量将开始流
端点 -> 节点

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +系统可以通过可配置的 :ref:`超额供给系数 <arch_overview_load_balancing_overprovisioning_factor>` 超额供给流量，目前默认值为 1.4（本文档中的默认值）。如果一个优先级中 80% 的端点是健康的，那么这个级别仍然被认为是完全健康的，因为 80 * 1.4 > 100。因此，P=0 级别端点将继续接收所有流量，直到只有不到 71.4%
个人认为，“可配置的”这几个字可以删掉

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +系统可以通过可配置的 :ref:`超额供给系数 <arch_overview_load_balancing_overprovisioning_factor>` 超额供给流量，目前默认值为 1.4（本文档中的默认值）。如果一个优先级中 80% 的端点是健康的，那么这个级别仍然被认为是完全健康的，因为 80 * 1.4 > 100。因此，P=0 级别端点将继续接收所有流量，直到只有不到 71.4%
直到只有不到 71.4% 的端点是健康的。
——》
直到健康的节点占比低于71.4%

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +优先级逻辑作用于产生整数型的健康分数。一个级别的健康分数是（该级别中健康主机的百分比）*（超额供给系数），上限为 100%。P=0 的端点收到（0 级的健康分数）% 的流量，其余的流量流向 P=1（假设 P=1 是 100% 健康的 — 后文再进一步说明）。例如，当 50% 的 P=0 端点是健康的，它们将收到 50 * 1.4 = 70% 的流量。每个优先级收到的流量的整数百分比，统称为系统的
优先级逻辑作用于产生整数型的健康分数-》 
优先级逻辑适用于整数健康分数。

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +优先级逻辑作用于产生整数型的健康分数。一个级别的健康分数是（该级别中健康主机的百分比）*（超额供给系数），上限为 100%。P=0 的端点收到（0 级的健康分数）% 的流量，其余的流量流向 P=1（假设 P=1 是 100% 健康的 — 后文再进一步说明）。例如，当 50% 的 P=0 端点是健康的，它们将收到 50 * 1.4 = 70% 的流量。每个优先级收到的流量的整数百分比，统称为系统的
一个级别
->
一个优先级级别

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +在考虑到了该级别最初的超额配置以及当前有多少端点是不健康的的之后，健康分数代表了该级别当前处理流量的能力。因此，如果所有级别的健康分数之和小于 100，那么 Envoy 认为没有足够的健康端点来完全处理流量。这个总和称为‘归一化总健康度“。当归一化总健康度降到 100 以下时，将各层的健康度分数归一化到该 100 以下的总分后再分配流量。如：健康度为 {20，30}（得出归一化的总健康度为 50
在考虑到了该级别最初的超额配置以及当前有多少端点是不健康的的之后，健康分数代表了该级别当前处理流量的能力。
-》
健康分数代表了该级别当前处理流量的能力，它会受该级别最初的超额配置以及当前有不健康节点数量所影响。

2020-11-24 11:02 UTC, Miss-you commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +在考虑到了该级别最初的超额配置以及当前有多少端点是不健康的的之后，健康分数代表了该级别当前处理流量的能力。因此，如果所有级别的健康分数之和小于 100，那么 Envoy 认为没有足够的健康端点来完全处理流量。这个总和称为‘归一化总健康度“。当归一化总健康度降到 100 以下时，将各层的健康度分数归一化到该 100 以下的总分后再分配流量。如：健康度为 {20，30}（得出归一化的总健康度为 50
并导致 {40%，60%} 的流量优先负载。
-》
最终流量优先负载为 {40%，60%} 。

2020-11-24 11:14 UTC, majinghe commented
@webup  参考下 yousa 给的建议。辛苦了。

2020-11-24 14:12 UTC, webup commented on docs/root/intro/arch_overview/upstream/load_balancing/priority.rst
> +在负载均衡过程中，Envoy 一般只会考虑处于最高优先级的主机。对于每个 EDS :ref:`LocalityLbEndpoints <envoy_v3_api_msg_config.endpoint.v3.LocalityLbEndpoints>` 还可以指定一个可选的优先级。当最高优先级（P=0）的端点是健康的，所有的流量将流转在该优先级的端点上。当最高优先级的端点变得不健康时，流量将开始流
这个先暂时不改了，我这边翻译的一系列目前都是翻成端点，如果确定要改之后我可以统一改一下～

2020-11-24 14:15 UTC, webup commented
> @webup 参考下 yousa 给的建议。辛苦了。

@Miss-you 感谢 comments，有一个回复，其它已按此修改

2020-11-25 10:13 UTC, merged