Add issue-96-redis translation.
cloudnativeto/envoy pull request #189
Opened 2020-11-22 09:33 UTC by hanyouqing

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] #96 
[Optional Deprecated:]

2020-11-22 13:17 UTC, zhangguanzhang commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Envoy 可以作为Redis代理，在集群的实例间对命令进行分区。在这种模式下， Envoy 的目标是在一致性前提下维护可用性和分区容错。这是 Envoy 和 `Redis Cluster
单词前后加空格

2020-11-22 13:17 UTC, zhangguanzhang commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* `Redis 协议 <https://redis.io/topics/protocol>`_ 编解码
超链接不用加反引号

2020-11-22 13:17 UTC, zhangguanzhang commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +出于被动健康检查的目的，连接超时，命令超时，连接关闭会被映射到5xx。所有来自 Redis 的其他响应都会被视为成功。
5xx加空格隔开

2020-11-23 03:08 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Envoy 可以作为Redis代理，在集群的实例间对命令进行分区。在这种模式下， Envoy 的目标是在一致性前提下维护可用性和分区容错。这是 Envoy 和 `Redis Cluster
Cluster 也要翻译的吧

2020-11-23 03:10 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Envoy 可以作为Redis代理，在集群的实例间对命令进行分区。在这种模式下， Envoy 的目标是在一致性前提下维护可用性和分区容错。这是 Envoy 和 `Redis Cluster
Cluster 也要翻译的吧

2020-11-23 03:18 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Redis Cluster 支持 (实验性)
Cluster 翻译
 支持（实验性）// 括弧前不需要再加空格，(实验性) 这个是英文括号么？

2020-11-23 03:18 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 集中节点的加入和离开
集群中节点的加入和离开

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 管控 :ref:`读请求路由<envoy_v3_api_field_extensions.filters.network.redis_proxy.v3.RedisProxy.ConnPoolSettings.read_policy>`. 仅适用于 Redis Cluster.
管控 :ref:`读路由请求  <envoy_v3_api_field_extensions.filters.network.redis_proxy.v3.RedisProxy.ConnPoolSettings.read_policy>` 仅适用于 Redis  集群。//1、读请求路由 ，后面加个空格；2、使用中文标点符号；3、Cluster也翻译

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +**Envoy Redis特性**:
**Envoy Redis 特性**: //空格

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +因为涉及 Reids，Redis 提供了一个全面的分区参考。请查看 "`分区: 如何在多个 Redis 实例间分片？
因为涉及 Reids，Redis 提供了一个全面的分区参考。
->
Redis 项目中提供了与 Redis 分区相关的全面参考。

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +<https://redis.io/topics/cluster-spec>`_ 关键差异。 Envoy 被设计为最优缓存，意味着它不会试图协调不一致的数据或者保持全局集群成员一致视图。它还支持基于不同的访问模式，驱逐或隔离需求，将命令从不同的工作负载路由到到不同的上游集群。
Envoy 被设计为尽力而为的缓存，

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +<https://redis.io/topics/cluster-spec>`_ 关键差异。 Envoy 被设计为最优缓存，意味着它不会试图协调不一致的数据或者保持全局集群成员一致视图。它还支持基于不同的访问模式，驱逐或隔离需求，将命令从不同的工作负载路由到到不同的上游集群。
将命令从不同的工作负载路由到不同的上游集群。

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 分离下游客户端和上游服务端认证
下游客户端和上游服务器分别进行身份验证。//这样易读性会不会更好一点？

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +**未来增强功能计划**：
计划的未来增强功能：//个人认为下文罗列的主体是功能
功能1
功能2
未来增强功能计划：
计划1
计划2

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 断路
circuit breaking 熔断？

2020-11-23 07:34 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 请求命令片段折叠
对分散的命令进行请求折叠？

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +如果使用:ref:`主动健康检查 <arch_overview_health_checking>`，集群需要配置 :ref:`自定义健康检查 <envoy_v3_api_field_config.core.v3。HealthCheck.custom_health_check>` 配置为 :ref:`Redis 健康检查<config_health_checkers_redis>`。
如果使用:ref:`主动健康检查 <arch_overview_health_checking>`，集群需要配置 :ref:`自定义健康检查 <envoy_v3_api_field_config.core.v3.HealthCheck.custom_health_check>` ，其配置为 :ref:`Redis 健康检查<config_health_checkers_redis>`。

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +如果使用被动健康检查，需要配置 :ref:`外部异常检测 <arch_overview_outlier_detection>`。
如果使用被动健康检查，需要配置 :ref:`异常检测 <arch_overview_outlier_detection>`。//外部？

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +出于被动健康检查的目的，连接超时，命令超时，连接关闭会被映射到5xx。所有来自 Redis 的其他响应都会被视为成功。
为了进行被动健康检查，需要将连接超时、命令超时和连接关闭都映射到 5xx 响应，而来自 Redis 的所有其他响应都视为成功。

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Envoy 现在对 `Redis 集群 <https://redis.io/topics/cluster-spec>`_ 提供实验性支持。
Envoy 目前为

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +当使用 Envoy 作为 Redis 集群的 sidecar 代理时，服务可以使用任意语言的非集群 Redis 客户端实现连接代理，如何连接但节点 Redis 实例。Envoy 代理会持续最总集群拓扑，并根据 `规则 <https://redis.io/topics/cluster-spec>`_ 发送命令到正确的 Redis 节点。像从副本读取的高级功能也可以增加到 Envoy 代理，不用变更
服务可以使用以任意语言实现的非集群 Redis 客户端连接到代理，就像它是一个单节点 Redis 实例一样。Envoy 代理将跟踪集群拓扑，并根据 `规范 <https://redis.io/topics/cluster-spec>`_  向集群中正确的 Redis 节点发送命令。还可以将高级功能（例如从副本中读取）添加到 Envoy 代理中，而不用更新每种语言的 Redis 客户端。

2020-11-23 08:05 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +Envoy 通过向集群中节点随机发送 `cluster slots <https://redis.io/commands/cluster-slots>`_ 命令追踪拓扑，并维护一下信息：
Envoy 通过定期向集群中的随机节点发送  `集群插槽 <https://redis.io/commands/cluster-slots>`_ 命令来跟踪群集的拓扑，并维护以下信息：

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +在命令级别，Envoy 仅支持可以被可靠的哈希到一台服务器的命令。只有 AUTH 和 PING 命令例外。如果下游配置了密码，AUTH 命令是被 Envoy 本地处理的，并且如果配置了密码，只有认证成功以后其他命令才会被处理。如果上游为整个集群配置了密码，Envoy 将在连接到上游服务器后透明底发送 AUTH 命令。Envoy 会立即为 PING 命令返回 PONG。PING 命令不接受参数。所
在命令级别，Envoy 仅支持可以被可靠地哈希到一台服务器的命令。只有 AUTH 和 PING 命令例外。如果下游配置了密码，Envoy 将在本地处理 AUTH，并且在配置了密码之后，在身份认证成功之前，Envoy 不会处理任何其他命令。

透明底 --》 透明地

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +如果 Redis 抛出错误，该错误将被传递给命令。Envoy 将 Redis 返回的错误数据响与数据类型应当作一个正常响应并回传给调用者。
如果 Redis 抛出错误，我们会将这个错误作为响应传递给命令。Envoy 将 Redis 返回的响应与错误数据类型视为正常响应，并将它传递给调用者。

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  no upstream host, "没有上游主机，环状哈希负载均衡器再为键选择环形位置上没有可用的健康主机"
再 --》 在

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  finished with n errors, "返回多个错误，如果收错误，分段命令将组合响应（如DEL命令）返回错误总数"
"返回多个错误，分段的命令将会组合多个响应(例如 DEL 命令)，如果收到任何错误，将返回接收到的错误总数"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  upstream protocol error, "上游协议错误，分段命令收到一个异常数据类型或一个不符合 Redis 协议的后端响应"
"上游协议错误，分段命令收到一个意外的数据类型或后端响应的数据不符合 Redis 协议"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  wrong number of arguments for command, "命令或参数数量错误，Envoy 命令参数检查失败"
"命令参数数量错误，Envoy 中的命令参数数量检查未通过"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  "NOAUTH Authentication required.", "需要认证，因下游设置认证密码且客户端没有认证通过导致命令被拒绝"
"NOAUTH 需要认证，因下游设置了认证密码且客户端没有认证成功，导致命令被拒绝"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  ERR invalid password, "密码无效，因密码无效导致命令认证失败"
"ERR 密码无效，因密码无效导致命令认证失败"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +  "ERR Client sent AUTH, but no password is set", "客户端发送认证，单未设置密码，收到认证命令，但是下游未设置密码"
"ERR 客户端发送了 AUTH，但未设置密码，收到认证命令，但没有配置下游认证密码"

2020-11-23 10:24 UTC, scilla0531 commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +使用 MGET 时，每个无法获取的 key 将会生成一个错误响应。例如：如果我们获取 5 个 key 的值，其中 2 个出现后端超时，我们将获得错信息替代每个出错key的值。
我们将会获得每个值的错误响应信息。

2020-11-24 10:26 UTC, majinghe commented
@hanyouqing   文档编译失败，麻烦在本地先编译一下，看一下错误在哪儿。一般都是格式问题。

2020-11-27 15:48 UTC, hanyouqing commented
> @hanyouqing 文档编译失败，麻烦在本地先编译一下，看一下错误在哪儿。一般都是格式问题。

@majinghe 编译问题修复，reviewer指出的问题修复，谢谢！

2020-11-28 04:38 UTC, hzliangbin requested changes
发现两处小问题，修改下。其它ok。

2020-11-28 04:38 UTC, hzliangbin commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> -`cluster slots <https://redis.io/commands/cluster-slots>`_ commands to a random node in the cluster, and maintains the
@scilla0531 cluster slot 应该就是redis可执行的一个命令，例如  `redis 127.0.0.1:6379> CLUSTER SLOTS  `这个可以不翻。

2020-11-28 04:38 UTC, hzliangbin commented on docs/root/intro/arch_overview/other_protocols/redis.rst
> +* 集中节点的加入和离开
集群节点的增加或减少

2020-11-28 05:11 UTC, hanyouqing commented
> 发现两处小问题，修改下。其它ok。

已修改，谢谢！

2020-11-28 05:12 UTC, zhangguanzhang commented
rebase成一个commit吧

2020-11-28 05:25 UTC, majinghe commented
@hanyouqing  可参照馆长说的 rebase 成一个 commit。

2020-11-28 06:02 UTC, hzliangbin approved these changes

2020-11-28 06:08 UTC, majinghe commented
/LGTM

2020-11-28 06:08 UTC, merged