zh-translation: <docs/root/intro/arch_overview/upstream/health_checking.rst>
cloudnativeto/envoy pull request #221
Opened 2020-11-29 05:19 UTC by mars-zhangcong

ref: https://github.com/cloudnativeto/envoy/issues/91>

- [x] Docs

2020-11-29 06:01 UTC, majinghe commented
@mars-zhangcong   CI 编译失败。需要查一下。

2020-11-29 08:48 UTC, mars-zhangcong commented
> @mars-zhangcong CI 编译失败。需要查一下。

已经重新push了，需要再提交PR吗？

2020-12-04 09:31 UTC, majinghe commented on docs/root/start/sandboxes/jaeger_tracing.rst
>  *************************
```suggestion
*****************
```

2020-12-04 09:31 UTC, majinghe commented on docs/root/start/sandboxes/jaeger_tracing.rst
>  *************************
*** 不要少于汉字即可。

2020-12-04 09:31 UTC, majinghe commented on docs/root/start/sandboxes/jaeger_tracing.rst
> +您现在可以通过 front-envoy 向 service1 发送以下请求:
```suggestion
你现在可以通过 front-envoy 向 service1 发送以下请求:
```
统一为你。

2020-12-05 08:43 UTC, mars-zhangcong commented on docs/root/start/sandboxes/jaeger_tracing.rst
>  *************************
已经 删除 *** 以适配 汉字长度

2020-12-05 08:44 UTC, mars-zhangcong commented on docs/root/start/sandboxes/jaeger_tracing.rst
> +您现在可以通过 front-envoy 向 service1 发送以下请求:
已经将文档中的 “您” 统一修改为“你”

2020-12-06 05:49 UTC, majinghe commented
@hzliangbin  麻烦看一下这个 PR。

2020-12-07 12:01 UTC, helight commented
为什么提交了2个文件呀

2020-12-09 07:03 UTC, hzliangbin commented
@majinghe 被冲掉了吗？

2020-12-09 07:55 UTC, majinghe commented
@hzliangbin 正在和翻译者沟通。

2020-12-09 13:00 UTC, hzliangbin requested changes

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +可以在每个上游群集的基础上 :ref:`配置 <config_cluster_manager_cluster_hc>` 主动运行健康检查。 如 :ref:`服务发现
可以在每个上游集群的基础上，

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +可以在每个上游群集的基础上 :ref:`配置 <config_cluster_manager_cluster_hc>` 主动运行健康检查。 如 :ref:`服务发现
Active health checking 主动健康检查，这样就可以了吧。参考下其他人建议。

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +<arch_overview_service_discovery>` 部分所述，主动运行健康检查和EDS服务发现类型是并行的。 但是，在其他情况下，即使使用其他服务发现类型，也需要进行主动健康检查。 Envoy支持三种不同类型的运行健康检查以及各种设置（检查时间间隔、主机不健康标记为故障、主机健康时标记为成功等）：
这里翻译成并行感觉还缺点意思，仔细看 服务发现 那章节，是说 Discovery Status 和 Health Check 的结果，共同起作用决定了路由结果。go hand in hand 有协作，配合的意思。这里可以酌情组织下语言。

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +* **Redis**: Envoy 将发送 Redis PING 命令并期望 PONG 响应。如果上游 Redis 服务器使用 PONG 以外的任何其他响应命令，则会导致健康检查失败。或者，Envoy 可以在用户指定的密钥上执行 EXISTS。如果密钥不存在，则认为它是合格的健康检查。这允许用户通过将指定的密钥设置为任意值来标记 Redis 实例以进行维护直至流量耗尽。请参阅
这里的key不宜翻译成密钥，结合上下文应该翻译成 key-value 中的意思，大意是检查redis中是否存在某个键，不存在，则健康检查通过。存在则失败。

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +运行健康检查通过为群集指定的传输套接字进行。这意味着，如果群集使用启用了TLS的传输套接字，则运行健康检查也将通过TLS进行。可以指定用于运行健康检查连接的 :ref:`TLS options <envoy_v3_api_msg_config.core.v3.HealthCheck.TlsOptions>` ，则此选项将很有用，如果相应的上游基于ALPN的 :ref:`FilterChainMa
群集->集群

2020-12-09 13:00 UTC, hzliangbin commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +健康检查身份
翻译成身份感觉欠妥，同一性？看下其它reviewer的建议。

2020-12-10 09:09 UTC, mars-zhangcong commented on docs/root/intro/arch_overview/upstream/health_checking.rst
> +可以在每个上游群集的基础上 :ref:`配置 <config_cluster_manager_cluster_hc>` 主动运行健康检查。 如 :ref:`服务发现
已经统一处理成为 主动健康检查

2020-12-13 15:28 UTC, mars-zhangcong commented
由于文件提交的有问题，目前已将文件并重新提交至#409 @hzliangbin 提出的问题都都进行了修改，感谢您的建议，谢谢！

2020-12-13 15:28 UTC, closed without merging