zh-translation:docs/root/start/sandboxes/_include/docker-env-setup.rst
cloudnativeto/envoy pull request #224
Opened 2020-11-29 11:37 UTC by majinghe

issue: #199

2020-12-01 09:09 UTC, hzliangbin requested changes

2020-12-01 09:09 UTC, hzliangbin commented on docs/root/start/sandboxes/_include/docker-env-setup.rst
> -The following documentation runs through the setup of Envoy described above.
run through 翻译成贯穿不太合适。参考[这里](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/run-through-sth)
下文罗列了准备 Envoy Docker编译环境的几个要点。（如上所述可能还要具体看前篇文章说了啥）

2020-12-02 01:05 UTC, majinghe commented on docs/root/start/sandboxes/_include/docker-env-setup.rst
> -The following documentation runs through the setup of Envoy described above.
这是个公共文件，到时候编译出来是用到其他文件中的，就能看到上下文是什么了。

2020-12-02 08:22 UTC, hzliangbin approved these changes

2020-12-02 09:59 UTC, addozhang commented on docs/root/start/sandboxes/_include/docker-env-setup.rst
> +确保你已安装较新版本的 ``docker`` 和 ``docker-compose`` 。
recent version 翻译成最新版本好点？

2020-12-02 10:54 UTC, majinghe commented on docs/root/start/sandboxes/_include/docker-env-setup.rst
> +确保你已安装较新版本的 ``docker`` 和 ``docker-compose`` 。
感觉较新版本能好点，最新版本的话，是不是容易让人理解， envoy 的编译必须是最新版本的 docker 才行呢，你觉得呢 晓辉？

2020-12-03 12:16 UTC, majinghe commented
@addozhang 晓辉，看一下这个 PR 还有没有什么问题。

2020-12-04 03:35 UTC, merged

2020-12-04 03:36 UTC, addozhang reviewed
LGTM