zh-translation:docs/root/install/sandboxes/local_docker_build.rst
cloudnativeto/envoy pull request #226
Opened 2020-11-29 13:56 UTC by majinghe

issue: #212

2020-12-01 08:19 UTC, hzliangbin requested changes

2020-12-01 08:19 UTC, hzliangbin commented on docs/root/install/sandboxes/local_docker_build.rst
> +如果你在任何 Dockerfile 中改变了 ``FROM`` 行，那么现在你可以使用这个 ``envoy`` 镜像来构建任何沙盒环境。
你可以在任意 Dockerfile 的 FROM 行中引用这个镜像，这样就可以基于这个envoy镜像构建出任意的沙盒环境。

2020-12-01 08:19 UTC, hzliangbin commented on docs/root/install/sandboxes/local_docker_build.rst
> +这个镜像包含所有构建 Envoy 所需的软件。从你的 Envoy 目录开始::
使用``envoyproxy/envoy-build`` 来编译 Envoy。
这个镜像包含构建 Envoy 所需的所有软件。

2020-12-02 01:03 UTC, majinghe commented
@hzliangbin 已参考 comment 进行修改。

2020-12-02 08:19 UTC, hzliangbin approved these changes

2020-12-02 09:43 UTC, scilla0531 commented on docs/root/install/sandboxes/local_docker_build.rst
> +以下步骤引导你构建自己的 Envoy 二进制包，并且将它放在一个干净的 Ubuntu 容器中。
二进制文件 是不是这种叫法更多一点呢？

2020-12-02 09:43 UTC, scilla0531 commented on docs/root/install/sandboxes/local_docker_build.rst
> +上述命令需要一点时间来执行因为它正在编译一个 Envoy 二进制包且要运行测试。
上述命令需要一点时间来执行，因为它要编译一个 Envoy 二进制文件并运行测试。

2020-12-03 12:17 UTC, majinghe commented on docs/root/install/sandboxes/local_docker_build.rst
> +以下步骤引导你构建自己的 Envoy 二进制包，并且将它放在一个干净的 Ubuntu 容器中。
确实是，翻译之初，脑海中没有浮现出这个。

2020-12-03 12:19 UTC, majinghe commented
@scilla0531 很棒的 review。 看一下还有没有要修改的地方。

2020-12-03 12:40 UTC, scilla0531 commented on docs/root/install/sandboxes/local_docker_build.rst
> +上述命令需要一点时间来执行因为它需要编译一个 Envoy 二进制文件并运行测试。
上述命令需要一点时间来执行，因为它需要编译一个 Envoy 二进制文件并运行测试。//这个地方是不是还是加上逗号好一点？

2020-12-03 12:40 UTC, scilla0531 commented on docs/root/install/sandboxes/local_docker_build.rst
> +上述命令需要一点时间来执行因为它需要编译一个 Envoy 二进制文件并运行测试。
以及本文件中还有两处Envoy binary，也统一翻译成二进制文件吧（目前还有两处是二进制包）？

2020-12-03 13:29 UTC, scilla0531 commented
/LGTM

2020-12-03 13:35 UTC, scilla0531 approved these changes

2020-12-03 13:36 UTC, merged