zh-translation: docs/root/intro/arch_overview/security/google_vrp.rst
cloudnativeto/envoy pull request #237
Opened 2020-12-05 04:53 UTC by li-guest

ref: https://github.com/cloudnativeto/envoy/issues/44

- [x] Docs

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +Envoy 是谷歌漏洞奖励计划的参与项目 `谷歌的漏洞奖励计划（VRP）
```suggestion
Envoy 是 `谷歌的漏洞奖励计划（VRP）` 的参与者。
```

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +2. 漏洞必须报告给 security@googlegroups.com，并保证具有潜在的安全问题的版本不被泄漏。提交报告时请遵循
```suggestion
2. 漏洞必须报告给 envoy-security@googlegroups.com，并保证具有潜在的安全问题的版本不被泄漏。提交报告时请遵循
```

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +   :repo:`披露指南 <SECURITY.md#disclosures>` 。披露 SLOs 被记录在 :repo:`这里 <SECURITY.md#fix-and-disclosure-slos>`。
```suggestion
   :repo:`披露指南 <SECURITY.md#disclosures>` 。披露 SLO 被记录在 :repo:`这里 <SECURITY.md#fix-and-disclosure-slos>`。
```
SLOs 是英语的复数，中文的话，就不需要了。

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +这有助于重新生成您自己的 Docker 基础镜像，来用于研究的目的。要在不依赖 CI 的情况下执行此操作，
```suggestion
这有助于重新生成你自己的 Docker 基础镜像，来用于研究的目的。要在不依赖 CI 的情况下执行此操作，
```
统一用你，不用您。

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +Docker 镜像包括 `gdb`, `strace`, `tshark` (欢迎通过 PRs 更新
Docker 镜像包括 `gdb`、`strace`、`tshark`

2020-12-08 10:30 UTC, majinghe commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* `-m 3g` 确保内存被限制到 3GB， 至少应该有这么多的内存可供执行环境使用。每个 Envoy 进程都有一个配置为限制在1GB的过载管理器。
* `-m 3g` 确保内存被限制到 3GB， 至少应该有这么多的内存可供执行环境使用。每个 Envoy 进程都有一个配置为限制在 1GB 的过载管理器。

2020-12-08 11:39 UTC, li-guest commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +Docker 镜像包括 `gdb`, `strace`, `tshark` (欢迎通过 PRs 更新
ok，明白，已经修改了。

2020-12-09 10:05 UTC, majinghe commented
/LGTM

2020-12-09 10:06 UTC, majinghe commented
@helight @addozhang @scilla0531 @hzliangbin 麻烦看一下这个 PR。

2020-12-10 15:24 UTC, hzliangbin requested changes

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +3. 漏洞必须不能事先在公共论坛上发表，比如，Github 的问题追踪，CVE 数据库（与 Envoy 关联的）等。
漏洞一定不能是公共论坛上已知的。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +3. 漏洞必须不能事先在公共论坛上发表，比如，Github 的问题追踪，CVE 数据库（与 Envoy 关联的）等。
现有的 CVE 之前没有与 Envoy 的漏洞关联的，不受影响。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +4. 漏洞也不能提交给谷歌或者 `Lyft <https://www.lyft.com/security>`_ 运行的并行奖励计划。
漏洞不能同时提交给由Google或Lyft运营的其它奖励计划。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* 不可信的上行流量。
upstreams 应该翻译成上游？

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +未来，我们可能会放宽这些限制，因为我们增加了复杂的程序执行的环境。
未来，随着程序运行环境的复杂度增加，我们可能会放宽上述这些限制。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> -We supply Docker images that act as the reference environment for this program:
this program 指代的是 VRP。翻译成该程序不合适，下文有几处也有这个问题。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +漏洞将在 10000 次的请求中被证明，这些请求触发了属于以下类别之一的故障模式：
联系上下文，可以推断这里的10000应该是指端口。 翻译成10000次请求不太合适。

2020-12-10 15:24 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* 在 OSS Envoy 安全团队的评判后，如果足够有趣的漏洞不属于上述类别，很可能属于高级别或关键级别的漏洞。
interesting有引人关注的意思，这里翻译成有趣不太合适。

2020-12-11 05:04 UTC, li-guest commented
非常感谢您的指正，已经修改了存在的问题。 @hzliangbin

2020-12-11 07:07 UTC, hzliangbin requested changes

2020-12-11 07:07 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +我们提供 Docker 镜像作为 VRP 运行的参考环境：
我们提供了 Docker 镜像作为漏洞奖励计划的运行参考环境：

2020-12-11 07:07 UTC, hzliangbin commented on docs/root/intro/arch_overview/security/google_vrp.rst
这一段话，表达的是这个意思：一个是Point release（数字版本，小数点版本）发现的漏洞使用一类镜像，一个是主分支发现的漏洞使用另一个镜像。数字版本的，要使用最新的数字版本。主分支的，要使用5天内的版本，来验证开发者提交的漏洞。如果5天内有公开披露的信息解决了这个漏洞了，那也不能参加的奖励计划了。
以上是一些评论和建议，酌情参考，可以适当组织下语言，不用拘泥于英语原文的表达，把意思说清楚，方便读者理解就行了。

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +   并附加了一个附加条件，即 VRP 报告（包括报告的电子邮件地址和姓名）可以基于 VRP 的目的与谷歌共享。
并附加了一个附加条件，即 VRP 报告 //并附加了一个条件

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +程序初始化阶段的攻击。我们排除了来自以下的威胁：
我们添加了一些临时的限制来约束 程序初始化阶段的攻击。// 约束和程序之间，多了个空格

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* 除了 HTTP 连接管理器网络过滤器和 HTTP 路由器过滤器意外的任何过滤器。
除了 HTTP 连接管理器网络过滤器和 HTTP 路由器过滤器意外的任何过滤器。 //意外->以外

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +  镜像是基于 Envoy 主分支构建的，只有在提交漏洞时最后 5 天内的版本才有资格使用 VRP。在该时间点上，它们不得受到任何公开披露的漏洞的影响。
使用 VRP //VRP 是个计划，是不是用参与/参加更好一点，比如：Envoy 是谷歌的漏洞奖励计划（VRP） 的参与者。（本文共两处）

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* OOM：请求导致边缘 Envoy 进程内存溢出，总共不应该有超过 100 个连接或流，否则会导致这种情况的发生（即暴力破解，不包括连接/流 DoS）。
edge Envoy ，本文有的地方翻译了有的地方没翻译，统一下吧？

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +执行环境的一个基本调用将在本地端口10000上调出 edge Envoy ，如下所示:
执行环境的一个基本调用将在本地端口10000上调出 edge Envoy ，如下所示: // 标点前后不用空格：Envoy，

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +  1. `/blockedz`: 返回 200 `hidden treasure`。除非存在一个合格的漏洞，否则 Envoy 边缘服务器的 10000 端口上的通信永远不可能接收到此响应。
//除非存在一个限定的漏洞，否则 Envoy 边缘服务器的 10000 端口上的流量永远不可能接收到此响应。//何为合格的漏洞？

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* OOM：请求导致边缘 Envoy 进程内存溢出，总共不应该有超过 100 个连接或流，否则会导致这种情况的发生（即暴力破解，不包括连接/流 DoS）。
OOM：导致边缘 Envoy 进程内存溢出的请求，连接或流总数不应超过 100 个，否则会导致这种情况的发生

2020-12-11 08:21 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* 绕过路由规则： 能够访问 `隐藏宝藏` 的请求。
绕过路由规则：能够访问 隐藏宝藏 的请求。//标点前后不需要加空格

2020-12-11 08:23 UTC, scilla0531 commented on docs/root/intro/arch_overview/security/google_vrp.rst
> +* OOM：请求导致边缘 Envoy 进程内存溢出，总共不应该有超过 100 个连接或流，否则会导致这种情况的发生（即暴力破解，不包括连接/流 DoS）。
@majinghe 小马哥，这篇中有多处edge Envoy，本文有的地方翻译了有的地方没翻译，是统一翻译还是统一不翻译呀？

2020-12-11 15:35 UTC, hzliangbin approved these changes

2020-12-13 03:09 UTC, majinghe commented
@li-guest  麻烦把多次 commit rebase成一个提交一下，然后我们修改一下。这个 commit 太多了。

2020-12-13 11:27 UTC, merged