#342 translate
cloudnativeto/envoy pull request #411
Opened 2020-12-11 01:29 UTC by addozhang

#342

2020-12-12 12:54 UTC, baobaoyeye commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +原始源监听器过滤器在 Envoy 的上游复制连接的下游远程地址。 例如，如果下游连接以IP地址 ``10.1.2.3`` 连接到 Envoy，则 Envoy 将以源 IP ``10.1.2.3`` 连接到上游。
```suggestion
在 Envoy 的上游侧，原始源监听器过滤器复制连接的下游远程地址。例如，如果下游连接以IP地址 ``10.1.2.3`` 连接到 Envoy，则 Envoy 将以源 IP ``10.1.2.3`` 连接到上游。
```

2020-12-12 13:45 UTC, baobaoyeye commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +使用的下游远程地址很可能是全局可路由的。 默认情况下，从上游主机返回到该地址的数据包将不会通过 Envoy 路由。必须将网络配置为强制将其 IP 被 Envoy 复制的所有流量都通过 Envoy 主机强制路由回去。
```suggestion
使用的下游远程地址很可能是全局可路由的。 默认情况下，从上游主机返回到该地址的数据包将不会通过 Envoy 路由。必须将网络配置为通过 Envoy 主机强制路由回所有 IP 被 Envoy 复制的流量。
```

2020-12-12 13:49 UTC, baobaoyeye commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
>  We can use the following set of commands to ensure that all ipv4 and ipv6 traffic marked with *X*
这部分英文要删掉？

2020-12-12 13:51 UTC, baobaoyeye commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +我们可以使用以下命令集来确保所有标有 *X*（在示例中假定为123）的 ipv4 和 ipv6 流量正确路由。 注意此示例假定 *eth0* 为
L：27-30 的英文应该删掉吧？

2020-12-12 13:55 UTC, baobaoyeye commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +如果 Envoy 和上游在同一主机上 -- 例如在 Sidecar 部署中，则可以使用 iptables 和路由规则来确保正确的行为。过滤器具有无符号整数配置，即 :ref:`mark <envoy_v3_api_field_extensions.filters.listener.original_src.v3.OriginalSrc.mark>` 。将此设置为 *X* 会导致 Envoy 用
值设置为0
-> 值设置为 0 // 数字前要空格？

2020-12-13 00:13 UTC, addozhang commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +如果 Envoy 和上游在同一主机上 -- 例如在 Sidecar 部署中，则可以使用 iptables 和路由规则来确保正确的行为。过滤器具有无符号整数配置，即 :ref:`mark <envoy_v3_api_field_extensions.filters.listener.original_src.v3.OriginalSrc.mark>` 。将此设置为 *X* 会导致 Envoy 用
是的 thx

2020-12-13 00:14 UTC, addozhang commented
感谢 review，已经做了修改。

2020-12-13 07:12 UTC, baobaoyeye approved these changes

2020-12-22 01:11 UTC, addozhang commented
@helight @majinghe 这个给再过一下

2020-12-22 14:52 UTC, smarkm requested changes

2020-12-22 14:52 UTC, smarkm commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +在 Envoy 的上游侧，原始源监听器过滤器复制连接的下游远程地址。例如，如果下游连接以IP地址 ``10.1.2.3`` 连接到 Envoy，则 Envoy 将以源 IP ``10.1.2.3`` 连接到上游。
原始源监听器过滤器复制 Enovy 上游端连接的下游远程地址。//是不是这样更好理解

2020-12-24 02:03 UTC, majinghe commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +* 这个过滤器通过名字 *envoy.filters.listener.original_src* 来配置
```suggestion
* 此过滤器的名称应该被配置为 *envoy.filters.listener.original_src*。
```
这个主要是为了前后统一，前面都这么翻译了。你的这个本身翻译没问题的。

2020-12-24 02:03 UTC, majinghe commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +在 Envoy 的上游侧，原始源监听器过滤器复制连接的下游远程地址。例如，如果下游连接以IP地址 ``10.1.2.3`` 连接到 Envoy，则 Envoy 将以源 IP ``10.1.2.3`` 连接到上游。
这个我感觉翻译者的能好点儿，断句语意能更清新一点。

2020-12-24 02:03 UTC, majinghe commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +我们可以使用以下命令集来确保所有标有 *X*（在示例中假定为123）的 ipv4 和 ipv6 流量正确路由。 注意此示例假定 *eth0* 为
```suggestion
我们可以使用以下命令集来确保所有标有 *X*（在示例中假定为 123）的 ipv4 和 ipv6 流量正确路由。 注意此示例假定 *eth0* 为
```

2020-12-24 02:03 UTC, majinghe commented on docs/root/configuration/listeners/listener_filters/original_src_filter.rst
> +我们可以使用以下命令集来确保所有标有 *X*（在示例中假定为123）的 ipv4 和 ipv6 流量正确路由。 注意此示例假定 *eth0* 为
> L：27-30 的英文应该删掉吧？
> 
> （在示例中假定为123）-》（在示例中假定为 123）

可以直接使用 suggestion 来添加 review，省事，好用。

2020-12-24 02:03 UTC, majinghe commented
@addozhang 晓辉，非常棒的翻译。多多翻译些。一些小建议。仅供参考。

2020-12-24 09:44 UTC, addozhang commented
@majinghe 已经更新 感谢 review

2020-12-24 13:32 UTC, smarkm approved these changes

2020-12-25 02:37 UTC, majinghe commented
/LGTM

2020-12-25 02:38 UTC, merged