zh-translation:docs/root/configuration/upstream/cluster_manager/clust…
cloudnativeto/envoy pull request #418
Opened 2020-12-13 10:40 UTC by majinghe

issue: #326

2020-12-15 09:48 UTC, hzliangbin requested changes

2020-12-15 09:48 UTC, hzliangbin commented on docs/root/configuration/upstream/cluster_manager/cluster_hc.rst
> +当检查响应时，"fuzzy" 匹配会被执行以确保找到每一个块，且按照指定的顺序，但不一定是连续的。因此，在上述的示例中，"04" 可以插在 "02" 和 "03" 的响应之间，且检查也将会通过。这么做是为了支持把不确定性数据，比如数据，插入响应中的协议。
such as time ，比如时间

2020-12-15 09:48 UTC, hzliangbin commented on docs/root/configuration/upstream/cluster_manager/cluster_hc.rst
> +较复杂的健康检查模式，诸如 send/receive/send/receive，现在还不可能。
现在还不支持

2020-12-17 08:04 UTC, smarkm commented
/review

2020-12-21 01:39 UTC, majinghe commented
> /review

@smarkm  直接利用 suggestion 或者添加 comment 的方式进行 review 即可。不用认领。

2020-12-21 01:43 UTC, majinghe commented
@hzliangbin 已参考修改。

2020-12-21 08:07 UTC, WisWang reviewed
提了一个小意见o(*￣︶￣*)o

2020-12-21 08:07 UTC, WisWang commented on docs/root/configuration/upstream/cluster_manager/cluster_hc.rst
> +在每一个健康检查周期内，所有的“发送”字节都会发送至目标服务器。
```suggestion
在每一个健康检查周期内，所有的 "send" 字节都会发送至目标服务器。
```

2020-12-22 02:27 UTC, hzliangbin approved these changes

2020-12-23 01:11 UTC, merged