zh-translation:docs/root/configuration/listeners/listener_filters/ori…
cloudnativeto/envoy pull request #451
Opened 2020-12-17 12:39 UTC by majinghe

issue: #252

2020-12-18 14:51 UTC, lut777 requested changes

2020-12-18 14:51 UTC, lut777 commented on docs/root/configuration/listeners/listener_filters/original_dst_filter.rst
> +当连接已经由 iptables REDIRECT 目标，或 iptables TPROXY 目标与监听器的 :ref:`透明 <envoy_v3_api_field_config.listener.v3.Listener.transparent>` 选项设置进行了重定向，原目的地监听器过滤器会读取 SO_ORIGINAL_DST 套接字选项设置。Envoy 中的后续处理会将恢复的目的地地址视为连
根据 https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-msg-config-listener-v3-listener 中 transparent 的定义, 在置 transparent 为 true 后, TProxy 会被启动并完成重定向. 因此在这里, 我认为 "使用iptables redirect" 和 "设置 transparent 为true 从而基于TProxy redirect" 是一个并列的关系.

2020-12-21 10:27 UTC, hzliangbin requested changes

2020-12-21 10:27 UTC, hzliangbin commented on docs/root/configuration/listeners/listener_filters/original_dst_filter.rst
> +当连接已经由 iptables REDIRECT 目标，或 iptables TPROXY 目标与监听器的 :ref:`透明 <envoy_v3_api_field_config.listener.v3.Listener.transparent>` 选项设置进行了重定向，原目的地监听器过滤器会读取 SO_ORIGINAL_DST 套接字选项设置。Envoy 中的后续处理会将恢复的目的地地址视为连
原目的地地集群 有误

2020-12-22 01:05 UTC, majinghe commented
@lut777 @hzliangbin PTAL

2020-12-22 01:41 UTC, hzliangbin approved these changes

2020-12-24 01:46 UTC, majinghe commented
@lut777 再次确认一下这个 PR

2020-12-24 02:18 UTC, lut777 approved these changes

2020-12-24 02:21 UTC, merged