zh-translation:docs/root/configuration/http/http_filters/cors_filter.rst
cloudnativeto/envoy pull request #485
Opened 2020-12-29 12:51 UTC by majinghe

issue: #275

2021-01-10 03:18 UTC, addozhang requested changes
看下这个空格要不要去掉。

2021-01-10 03:18 UTC, addozhang commented on docs/root/configuration/http/http_filters/cors_filter.rst
> +<envoy_v3_api_field_config.core.v3.RuntimeFractionalPercent.runtime_key>` 值来配置。仅当在影子模式下启用时，过滤器将评估请求的 *来源* 来决定它是否是有效的，但不会强制执行任何策略。
```suggestion
<envoy_v3_api_field_config.core.v3.RuntimeFractionalPercent.runtime_key>` 值来配置。仅当在影子模式下启用时，过滤器将评估请求的*来源*来决定它是否是有效的，但不会强制执行任何策略。
```
记得这种空格可以不加。

2021-01-11 01:05 UTC, majinghe commented on docs/root/configuration/http/http_filters/cors_filter.rst
> +<envoy_v3_api_field_config.core.v3.RuntimeFractionalPercent.runtime_key>` 值来配置。仅当在影子模式下启用时，过滤器将评估请求的 *来源* 来决定它是否是有效的，但不会强制执行任何策略。
嗯，这种不需要，就是用vim翻译的时候，加空格能看到后面的效果，我删除一下。

2021-01-11 01:09 UTC, addozhang approved these changes
/LGTM

2021-01-11 01:10 UTC, majinghe commented
@addozhang 已参考修改。

2021-01-11 08:06 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/cors_filter.rst
> +  没有来源头部的请求将不会出现在统计信息中。
Origin 是不是不翻译更好一点呢？

2021-01-11 11:54 UTC, majinghe commented on docs/root/configuration/http/http_filters/cors_filter.rst
> +  没有来源头部的请求将不会出现在统计信息中。
这个其他文章里面都翻译了。感觉还是翻译吧。

2021-01-12 11:40 UTC, majinghe commented
@scilla0531 看一下这个 PR 是否还有问题。

2021-01-12 12:58 UTC, merged