zh-translation:docs/root/configuration/http/http_filters/ip_tagging_filter.rst
cloudnativeto/envoy pull request #489
Opened 2020-12-30 04:57 UTC by li-guest

ref: https://github.com/cloudnativeto/envoy/issues/302

- [x] Docs

2020-12-31 01:54 UTC, addozhang reviewed
加了点建议，不一定对，参考一下。

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +HTTP IP 标记过滤器使用来自 :ref:`x-forwarded-for <config_http_conn_man_headers_x-forwarded-for>` 的受信任地址的字符串标记
```suggestion
HTTP IP 标记过滤器为来自 :ref:`x-forwarded-for <config_http_conn_man_headers_x-forwarded-for>` 的受信任地址使用字符串标记
```

ip tag 的功能是在 ip tag filter 中这只 ip list，当 x-forwarded-for 的 ip 符合条件时就会为这个请求设置 x-envoy-ip-tags: [tag filter 中设置的tag]。所以我觉得目标主题要翻译清楚(for xxx)

![image](https://user-images.githubusercontent.com/2224492/103389857-490b3100-4b4c-11eb-8b55-d570b073fef6.png)

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +IP 标记的实现提供了一种可伸缩的方法，可以有效地将 IP 地址与大量的 CIDR 进行比较。存储标签和 IP 地址子网的底层算法是 S.Nilsson 和
```suggestion
IP 标记的实现提供了一种可伸缩的方法，可以高效地将 IP 地址与大量的 CIDR 进行比较。存储标签和 IP 地址子网的底层算法是 S.Nilsson 和
```

这里讲的是底层的实现算法，我认为 efficiently 应翻译成 “高效地”

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +中描述的一种级别的 trie。
```suggestion
中描述的一种 Level-Compressed trie。
```
Level-Compressed trie 这个该怎么翻译，要不要保持原文；trie 没找到这个单词 。。

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +        total, Counter, 操作 IP 标记过滤器的请求总数
```suggestion
        total, Counter, IP 标记过滤器操作的请求总数
```

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +        no_hit, Counter, 没有应用 IP 标记的请求总数
```suggestion
        no_hit, Counter, 不适用 IP 标记的请求总数
```

2020-12-31 01:54 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +    为启用过滤器请求的百分比。默认值为 100。
```suggestion
    启用过滤器的请求的百分比。默认值为 100。
```

2020-12-31 02:57 UTC, addozhang commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +中描述的一种级别的 trie。
@helight @majinghe 来看下这个要不要翻译？

2020-12-31 02:59 UTC, li-guest commented
感谢您的建议，已经修改了部分建议。 @addozhang

2021-01-02 06:37 UTC, lut777 requested changes

2021-01-02 06:37 UTC, lut777 commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +中描述的一种级别的 trie。
tire 是 tire-tree 的缩写. 
论文原文如下: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.132.4190&rep=rep1&type=pdf 
在第五页的例子中可以明显地看到 tire-tree 的结构. 
Level-Compressed 我猜测应该是压缩树高度的意思.

2021-01-02 06:44 UTC, lut777 commented on docs/root/configuration/http/http_filters/ip_tagging_filter.rst
> +中描述的一种级别的 trie。
建议写成 压缩 tire 树, 参考论文及linux实现.

2021-01-03 17:30 UTC, lut777 approved these changes

2021-01-04 01:26 UTC, merged