zh-translation:docs/root/configuration/http/http_conn_man/response_code_details.rst
cloudnativeto/envoy pull request #491
Opened 2020-12-30 06:47 UTC by li-guest

ref: https://github.com/cloudnativeto/envoy/issues/264

- [x] Docs

2020-12-30 08:53 UTC, li-guest commented
本次翻译任务主要遇到两个问题：

1. 遇到特定的术语的情况，比如 header，是否翻译？我这里翻译成了**标头**；
2. 遇到原始英文文档中的两个问题：一是单词错误，二是重复的内容；

2020-12-30 08:54 UTC, li-guest commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   response_payload_too_large, Envoy 正在执行非流代理，响应的负载超出了配置的限制。
在原始的英文文档中，有两行一样的说明。

2020-12-30 08:58 UTC, li-guest commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +    http2.invalid.header.field, 其中一个 HTTP/2 标头无效。
此处，**header** 翻译成了 **标头**，后面还有许多类似的地方。

2021-01-13 11:05 UTC, majinghe commented
@li-guest 
1 header 翻译成头部
2 原文有问题的，在这个 issue：https://github.com/cloudnativeto/envoy/issues/441 中记录下来，最终统一给上游提问题。

2021-01-13 11:06 UTC, majinghe commented
@zhiguo-lu 治国，辛苦 review 一下这个 PR。

2021-01-13 15:17 UTC, zhiguo-lu reviewed
同学，后面列表中有些语句，读着不是很顺，如果能优化一下就更完美了。

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +:ref:`自定义头部<config_http_conn_man_headers_custom_request_headers>` 配置了 _%RESPONSE_CODE_DETAILS_，
```suggestion
:ref:`自定义头部<config_http_conn_man_headers_custom_request_headers>` 配置了 _%RESPONSE_CODE_DETAILS%_，
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +Envoy 将传达一个给定流结束的详细原因。此页列出了 HttpConnectionManager、路由器过滤器和编解码器发送的详细信息。
```suggestion
Envoy 将针对一个指定的、已经结束的流，给出详细原因。另外，由 HttpConnectionManager、路由过滤器、和解码器发送的详细信息，将在本页列示。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +但这是不全面的，因为其他任何过滤器都可能会发送带有自定义详细信息的本地答复。
```suggestion
但此列表并不全面，这是因为其他过滤器也可以发送带有自定义细节的本地答复。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +下面列出了 HttpConnectionManager 或路由器过滤器可能会发送的响应或重置流的原因。
```suggestion
下面是 HttpConnectionManager 或路由过滤器可能会发送的响应或重置流的原因列表。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   absolute_path_rejected, 由于在不支持请求的路由上使用绝对路径，请求被拒绝。
```suggestion
   absolute_path_rejected, 由于在不支持绝对路径的路由上使用绝对路径，请求被拒绝。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +Envoy 将传达一个给定流结束的详细原因。此页列出了 HttpConnectionManager、路由器过滤器和编解码器发送的详细信息。
建议：路由器过滤器-》路由过滤器
以下内容建议酌情修改。

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   stream_idle_timeout, 已超出每个流的 keepalive 超时时间。
```suggestion
   stream_idle_timeout, 已超出每个长连接流的超时时间。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   upgrade_failed, 由于请求一个受支持的升级，请求被拒绝。
```suggestion
   upgrade_failed, 由于请求一个不受支持的升级，请求被拒绝。
```

2021-01-13 15:17 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +    http2.too_many_headers, headers（或 trailers）的数量超过了配置的限制。
```suggestion
    http2.too_many_headers, 头部（或尾部）的数量超过了配置的限制。
```

2021-01-13 15:17 UTC, zhiguo-lu commented
> 
> 
> @zhiguo-lu 治国，辛苦 review 一下这个 PR。

my pleasure

2021-01-13 15:21 UTC, zhiguo-lu commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +    http2.invalid.header.field, 其中一个 HTTP/2 标头无效。
标头这个词很少见，容易被误解。用小马哥推荐的“头部”，或者更详细一点，用“消息头”之类的都行。

2021-01-18 12:52 UTC, majinghe commented
@li-guest 参考治国的 review 信息，修改一下。辛苦

2021-01-19 05:46 UTC, zhiguo-lu commented
thanks for your work.
/lgtm

2021-01-28 09:15 UTC, WisWang reviewed
你这个文章中header翻译成了头，头部，标头三种，建议统一一下

2021-01-28 09:15 UTC, WisWang commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +Envoy 将针对一个指定的、已经结束的流，给出详细原因。另外，由 HttpConnectionManager、路由过滤器、和解码器发送的详细信息，将在本页列示。
```suggestion
Envoy 会给出指定流结束的详细原因。另外，由 HttpConnectionManager、路由过滤器、和编解码器发送的详细信息，将在本页列示。
```
codec 我看你下面都翻译成了编解码。

2021-01-28 09:15 UTC, WisWang commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +Http2 相信信息
这行就不用说是啥了吧。。。

2021-01-28 09:15 UTC, WisWang commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +所有 http2 的详细信息都源于 *http2.*
```suggestion
所有 http2 的详细信息都以 *http2.* 为根。
```
root 翻译成前缀和根都行吧，源于感觉差点意思

2021-02-02 13:58 UTC, majinghe commented
@li-guest 辛苦 参考 comment 处理一下。 root 翻译成根吧。

2021-02-05 01:56 UTC, majinghe commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +Http2 相信信息
这个应该是详细信息吧。

2021-02-05 01:57 UTC, majinghe commented
@WisWang 辛苦泓智看一下这个 PR，看一下是否ok。

2021-02-05 02:02 UTC, majinghe reviewed
相信 我帮你直接改成了详细。我这边没有其他问题了，

2021-02-05 14:05 UTC, li-guest commented
已经更正全部内容，感谢各位指正。

2021-02-06 03:47 UTC, WisWang commented
@li-guest 我看你修改文件的84，87行好像没改呀。。。

2021-02-07 06:01 UTC, WisWang commented
我上面就是简单看了一下，你自己再一个个查下吧，45行，20行，都没改呢。。。

2021-04-01 22:52 UTC, addozhang commented
@WisWang 再 review 下，辛苦了

2021-04-02 05:35 UTC, WisWang requested changes

2021-04-02 05:35 UTC, WisWang commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   absolute_path_rejected, 由于在不支持请求的路由上使用绝对路径，请求被拒绝。
```suggestion
   absolute_path_rejected, 由于在不支持绝对路径的路由上使用绝对路径，请求被拒绝。
```

2021-04-02 05:35 UTC, WisWang commented on docs/root/configuration/http/http_conn_man/response_code_details.rst
> +   upgrade_failed, 由于请求一个受支持的升级，请求被拒绝。
```suggestion
   upgrade_failed, 由于请求一个不受支持的升级，请求被拒绝。
```

2021-04-02 05:37 UTC, WisWang commented
/LGTM

2021-04-02 05:50 UTC, WisWang approved these changes

2021-04-02 05:51 UTC, merged