zh-translation: docs/root/operations/hot_restarter.rst
cloudnativeto/envoy pull request #526
Opened 2021-01-11 13:24 UTC by vgbhfive

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes: docs/root/operations/hot_restarter.rst
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]  #513
[Optional Deprecated:]

2021-01-12 11:11 UTC, lut777 requested changes

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
> +通常情况下，在配置修改或二进制升级后，Envoy 将会 :ref:`热重启 <arch_overview_hot_restart>` 。然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。所以我们提供 :repo:`/restarter/hot-restarter.py` 来简化这个流程。
for config changes and binary updates/配置修改或二进制升级后
这个翻译有点太死板了. 我觉得写成 配置或代码变更 更直接一点...

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
> +通常情况下，在配置修改或二进制升级后，Envoy 将会 :ref:`热重启 <arch_overview_hot_restart>` 。然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。所以我们提供 :repo:`/restarter/hot-restarter.py` 来简化这个流程。
然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。
本句不通.

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
> +`start_envoy.sh` 可以被这样定义，例如（使用 salt/jinja 语法）：
"可以按如下方法定义" "类salt/jinja语法"

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
留意 `inotify.max_user_watches` 
当 Envoy 被用于监视 Linux 目录中的多个配置文件时, 请增加此值. 因为 Linux 限制了最大可监视文件数量.

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
> +*RESTART_EPOCH* 环境变量由重启程序在每次重启的时候设置，并且必须传递给 :option:`--restart-epoch` 选项。
并且必须通过 :option:`--restart-epoch` 选项完成传递

2021-01-12 11:11 UTC, lut777 commented on docs/root/operations/hot_restarter.rst
> +   然后在后续的调用中作为 :option:`--base-id` 的值（当 *RESTART_EPOCH* 大于 0 时），这样才能设置该标志。
并且你的 *start_envoy.sh* 必须获得所选的基本 ID（例如 :option:`--base-id-path` ）并存储，
这样才能设置该标志  =>  才能设置该标志

2021-01-15 06:20 UTC, lut777 approved these changes

2021-01-15 13:47 UTC, smarkm commented on docs/root/operations/hot_restarter.rst
> +通常情况下，在配置修改或二进制升级后，Envoy 将会 :ref:`热重启 <arch_overview_hot_restart>` 。然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。所以我们提供 :repo:`/restarter/hot-restarter.py` 来简化这个流程。
通常情况下，在配置修改或二进制升级后，Envoy 将会 :ref:`热重启 <arch_overview_hot_restart>` 。然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。所以我们提供 :repo:`/restarter/hot-restarter.py` 来简化这个流程

2021-01-15 13:52 UTC, smarkm commented on docs/root/operations/hot_restarter.rst
> +通常情况下，在配置修改或二进制升级后，Envoy 将会 :ref:`热重启 <arch_overview_hot_restart>` 。然而，在许多情况下，用户希望通过标准的流程管理器，例如 monit、runit 等。所以我们提供 :repo:`/restarter/hot-restarter.py` 来简化这个流程。
删除句尾 `。`

2021-01-15 13:52 UTC, smarkm commented on docs/root/operations/hot_restarter.rst
> +`start_envoy.sh` 可以被这样定义，例如（使用 salt/jinja 语法）：
赞同原文翻译

2021-01-15 13:52 UTC, smarkm commented on docs/root/operations/hot_restarter.rst
> +   然后在后续的调用中作为 :option:`--base-id` 的值（当 *RESTART_EPOCH* 大于 0 时），这样才能设置该标志。
删除句尾 `。`

2021-01-18 12:49 UTC, majinghe commented on docs/root/operations/hot_restarter.rst
> +   然后在后续的调用中作为 :option:`--base-id` 的值（当 *RESTART_EPOCH* 大于 0 时），这样才能设置该标志。
@smarkm 不是很理解，删除句号。能够用 suggestion 标注一下。

2021-02-02 13:53 UTC, majinghe commented
/LGTM

2021-02-02 13:54 UTC, merged