zh-translation:  docs/root/configuration/http/http_filters/gzip_filter.rst
cloudnativeto/envoy pull request #618
Opened 2021-01-17 13:52 UTC by llhhbc

ref: https://github.com/cloudnativeto/envoy/issues/263

- [x] Docs

2021-01-18 01:49 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
这个过滤器已弃用，改用 :ref:`HTTP Compressor filter <config_http_filters_compressor>`。

2021-01-18 01:54 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +  这个过滤器已弃用，改用
这个过滤器已弃用，改用 :ref:HTTP Compressor filter <config_http_filters_compressor>。

2021-01-18 01:57 UTC, scilla0531 requested changes

2021-01-18 01:57 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +  :ref:`HTTP Compressor filter <config_http_filters_compressor>`
这个过滤器已弃用，改用 :ref:HTTP Compressor filter <config_http_filters_compressor>。

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
这个过滤器已弃用，改用 :ref:`HTTP Compressor filter <config_http_filters_compressor>`。//行末句号

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
* :ref:`v3 API 参考 <envoy_v3_api_msg_extensions.filters.http.gzip.v3.Gzip>` * 这个过滤器的名称应该配置为 *envoy.filters.http.gzip*。

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +
多了一行空行

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +- 请求头中 *accept-encoding* 取值包含“gzip” or “\*”但权重配置“q=0”
or 也翻译下

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +所有配置Gzip压缩过滤器的指标前缀为 <stat_prefix>.gzip.*
Gzip //英文前后的空格

2021-01-18 02:21 UTC, scilla0531 commented on docs/root/configuration/http/http_filters/gzip_filter.rst
> +  not_compressed_etag, Counter, 由于扩展报文头而未进行压缩的请求数。只有当开启 *disable_on_etag_header* 时才有该指标
原文行末是有标点的（其实也可以都不加，但最好统一下，有的行加有的行不加看上去不太友好），且应该使用中文标点。

2021-01-18 02:23 UTC, scilla0531 commented
@llhhbc 很棒的翻译，几乎无可挑剔，提了几个格式相关的建议。

2021-01-19 14:11 UTC, closed without merging

2021-01-19 14:25 UTC, llhhbc commented
> @llhhbc 很棒的翻译，几乎无可挑剔，提了几个格式相关的建议。

你好，因为我提mr不是基于默认分支，force push后无法自动更新，关闭了无法再打开，所以我重新提了个mr： https://github.com/cloudnativeto/envoy/pull/629