zh-translation: docs/root/faq/debugging/why_is_envoy_404ing_connect_r…
cloudnativeto/envoy pull request #731
Opened 2021-04-04 15:16 UTC by vgbhfive

…equests.rst

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes: docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue] #693
[Optional Deprecated:]

2021-04-06 01:25 UTC, helight approved these changes
LGTM

2021-04-09 12:48 UTC, lut777 commented on docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
> +为什么 Envoy 会发送 404 连接请求？
404 是给 CONNECT 请求的回复吧?

2021-04-09 12:50 UTC, lut777 commented on docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
> +由于 CONNECT 请求（通常）不会携带路径，所以大多数匹配器去匹配 CONNECT 请求都会失败，而 Envoy 会发送 404 是由于未找到对应的路由。
我觉得这里的 "Envoy will send a 404 " 翻译成 Envoy会回复404 会更好...

2021-04-09 12:51 UTC, lut777 requested changes
我认为 404 是 matcher 给 request 发送方的回复. 
所以在翻译中应该体现这一点.

2021-04-15 14:33 UTC, vgbhfive commented
> 我认为 404 是 matcher 给 request 发送方的回复.
> 所以在翻译中应该体现这一点.

这里的翻译是以 Envoy 自身为出发点，站在 Envoy 的角度进行的翻译。不过你的建议可以让大家更好理解。我会修改的，感谢。

2021-04-17 02:31 UTC, majinghe commented on docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
> +为什么 Envoy 会发送 404 连接请求？
应该是 Envoy 为什么发送 404 给连接请求？send .... to ，把什么发送给什么。也可以理解为  404 是连接请求的回复。

2021-04-17 02:33 UTC, majinghe commented on docs/root/faq/debugging/why_is_envoy_404ing_connect_requests.rst
> +为什么 Envoy 会为连接请求响应 404？
Envoy 为什么会发送 404 给连接请求？

这样是不是更顺畅点。

2021-04-17 02:33 UTC, majinghe commented
@vgbhfive 一点小建议。仅供参考。

2021-04-18 10:21 UTC, lut777 approved these changes

2021-04-19 01:36 UTC, majinghe commented
/LGTM

2021-04-19 01:36 UTC, merged